// Encrypted GitHub upload token, unlocked in-browser by a passcode.
// Replace this with the blob generated by encrypt-setup.html (run locally).
// While null, the tour falls back to a manual token prompt (⚙).
window.__GH_ENC = null;
