"""Editorial content for the Proposed / brick local review edition.

Dimensions describe the current model, not a construction specification.
The shared page list also drives gallery ordering and image captions.
"""

# Support direct Python/Blender entry points as well as package imports.
import sys as _sys
from pathlib import Path as _Path
_sys.path.insert(0, str(_Path(__file__).resolve().parents[2]))

def room(chapter, title, subtitle, images, sections, facts, note):
    return dict(kind='room', chapter=chapter, title=title, subtitle=subtitle,
                images=images, sections=sections, facts=facts, note=note)


PAGES = [
    dict(kind='cover', chapter='The house', title='A considered home', images=['front-brick']),
    dict(kind='contents', chapter='The house', title='A home, room by room', images=[]),
    room('The house', 'Brick, shadow and a welcoming arrival',
         'The complete Proposed design, presented with brick house facades and a dark grey roof.',
         ['front-brick'],
         [('A coherent exterior', 'Warm brick connects the original house and extensions, with darker roof tiles and restrained joinery. The entrance link keeps its established position and angle, preserving the relationship between the house, garage and forecourt.'),
          ('The chosen finish', 'Brick applies to the house and extensions. Dormer faces and cheeks remain tiled; internal wall faces stay ivory. Garden buildings retain their own finishes. The roof terrace and pool garden belong to this complete Proposed design.')],
         ['Brick house and extensions', 'Dark grey roof tiles', 'Tiled dormer faces and cheeks'],
         'Four outdoor parking spaces complement the double garage; the entrance remains a separate pedestrian destination.'),
    dict(kind='plan', chapter='Floorplans', title='Ground floor', level='ground', images=[],
         subtitle='Arrival, connected living and the practical rooms that support everyday life.',
         sections=[('Arrive', 'The entrance gallery links the garage wing to the original hall. The gym and utility sit close to this everyday entrance.'),
                   ('Gather', 'Kitchen and garden dining connect with the TV lounge. Formal lounge and dining retain their own quieter setting in the original house.'),
                   ('Work and organise', 'The original office, cloakroom and fitted arrival storage serve the ground floor without turning the living rooms into circulation spaces.')],
         note='House footprint only. The pool, garden buildings, workshop and forecourt are described in the garden and garage chapters.'),
    dict(kind='plan', chapter='Floorplans', title='First floor', level='first', images=[],
         subtitle='A private principal suite, family bedrooms and a lounge opening onto the roof terrace.',
         sections=[('Principal suite', 'Bed, sofa and study occupy one generous room. The walk-through wardrobe and enlarged bathroom sit along the approach.'),
                   ('Family and guests', 'The guest room, Bedrooms 2, 3 and 4 and the enlarged side bedroom share the original house and side wing. Most bedroom groups have an ensuite.'),
                   ('Shared space', 'A family lounge and bathroom sit beside the connecting halls. The terrace remains part of Proposed, with its doors and rooflights kept clear.')],
         note='The bathroom extension and wardrobe shift include moving both affected windows 0.75 m toward the bed.'),
    dict(kind='plan', chapter='Floorplans', title='Loft level', level='loft', images=[],
         subtitle='A separate bedroom suite above the principal room and a flexible hobby room over the original house.',
         sections=[('A second retreat', 'The loft bedroom and ensuite use the dormer volume above the principal bedroom. Low eaves are kept distinct from standing space.'),
                   ('Make, read, relax', 'The original-house loft has a mobile project table, storage and informal seating. The central route connects back to the loft landing.'),
                   ('Headroom to resolve', 'The existing bridge has approximately 1.78-1.90 m clear headroom. It remains an unresolved design constraint, not a full-height route.')],
         note='Roof slopes are not full-height walls. Read this plan with the model sections before reviewing loft access or headroom.'),
    dict(kind='plan', chapter='Floorplans', title='Lower ground floor', level='basement', images=[],
         subtitle='Cinema, drinks and games arranged around the retained stair and lobby.',
         sections=[('Cinema', 'Four deep seats face a fixed screen. Storage sits behind the seating, with the main approach along the side.'),
                   ('Wine bar', 'An oak and limestone dry bar provides three stools, concealed cooling and a separate TV sitting area.'),
                   ('Games', 'Pool and darts have distinct activity zones. Their occupied clearances are more demanding than the static furniture footprints shown here.')],
         note='Furniture and door positions are model-derived. Activity clearances are discussed on the room pages; this is not a construction drawing.'),
    room('Arrival & living', 'The entrance gallery',
         'A useful arrival sequence, softened by oak, limestone and pools of warm light.',
         ['arrival'],
         [('Space to arrive', 'The double-height entrance stays open around the front door. A shallow coat cabinet wraps the corner instead of projecting into the middle of the hall. End-on hanging makes the reduced depth useful.'),
          ('A place for the everyday', 'A shoe bench sits beneath the internal gym window, with concealed storage close to the entrance. Opal pendants remain high in the entrance volume; quiet niches and stone objects add detail along the connecting gallery.')],
         ['320 mm deep corner storage', '1.43 m shoe bench', 'Pendant globes above 3 m'],
         'The coat cabinet follows the wall corner and keeps the entrance route legible.'),
    room('Arrival & living', 'The original staircase',
         'The familiar stair, updated with quieter materials and a more continuous handrail.',
         ['original-stair'],
         [('Retain the structure', 'The original flight keeps its location and structural form. Pale oak treads, ivory risers and a light stringer make the stair feel connected to the new rooms.'),
          ('A consistent detail', 'Slim bronze balusters support the polished oak handrail. The handrail sections have been aligned at their junctions so the line continues around the landing. Coordinated oak hall doors complete the same restrained material language.')],
         ['Existing stair position retained', 'Oak treads and continuous handrail', 'Ivory risers, bronze balusters'],
         'The stair is treated as part of the entrance composition, with clear floor space at its foot.'),
    room('Arrival & living', 'Kitchen and garden dining',
         'The accepted kitchen palette becomes the centre of the house.',
         ['kitchen'],
         [('Cook and gather', 'A generous island anchors the kitchen, with the working run and tall appliances close by. The garden dining area extends the view toward the glazing and gives the everyday table its own pool of light.'),
          ('Material continuity', 'Pale oak cabinetry, honed limestone and soft ivory carry through the connected spaces. Bronze fittings, opal pendants and carefully placed plants add warmth without competing with the long sightlines.')],
         ['Large island and garden dining', 'Pale oak, limestone and ivory', 'Bronze fittings and opal lighting'],
         'The adjacent TV lounge stays part of the same composition while giving the sofa a dedicated viewing position.'),
    room('Arrival & living', 'Details that make the kitchen',
         'Appliances and working surfaces receive the same attention as the larger composition.',
         ['kitchen-oven', 'kitchen-sink'],
         [('The appliance wall', 'Stacked black ovens sit within the oak cabinetry. Individual control knobs, digital clock displays, handles and door frames give the appliance elevation depth and a believable working scale.'),
          ('The sink and counter', 'An undermounted metal sink keeps the limestone worktop line clean. A bronze tap, drained surfaces and restrained accessories make this a practical working area. The nearby internal hatch remains an interior connection.')],
         ['Detailed oven controls', 'Undermounted sink and bronze tap'],
         'These close views show the intended finish quality; appliance models and stone selection remain part of later specification.'),
    room('Arrival & living', 'The TV lounge',
         'A relaxed corner of the open living space with its own clear focus.',
         ['tv-lounge'],
         [('A settled viewing position', 'The curved sofa faces a fixed television on a solid wall. A low oak media console and soundbar keep the screen composition simple, with stone tables close enough to use from the seats.'),
          ('Softness around the edges', 'An ivory rug and textured upholstery distinguish the sitting area from the kitchen circulation. Plants soften the transition to the garden side without filling the passage between rooms.')],
         ['Fixed television', 'Curved ivory sofa', 'Low oak media storage'],
         'The screen belongs to the seating group; passing through the room does not become the main activity in front of it.'),
    room('Arrival & living', 'The formal lounge',
         'A quieter room for conversation, arranged around the original character of the house.',
         ['formal-lounge-final'],
         [('A conversational centre', 'Two facing sofas create an intimate group around an oval stone coffee table. The retained fireplace and bay remain the room\'s architectural anchors, with a reading chair offering a separate place to sit.'),
          ('Connected, but distinct', 'The dining area remains in the same original room. Arched doors and existing openings are retained, while coordinated oak joinery and ivory upholstery link the formal space to the rest of the house.')],
         ['Two 2.40 m sofas', 'Original fireplace and bay', 'Separate reading position'],
         'The kitchen hatch remains an internal feature; it is not treated as another garden window.'),
    room('Arrival & living', 'Formal dining and the drinks cabinet',
         'Six comfortable everyday places, with space to extend for a larger evening.',
         ['formal', 'drinks'],
         [('A table that adapts', 'The 1.80 x 1.00 m table seats six regularly and extends to 2.80 m for eight to ten. A nearby sideboard stores the two extension leaves and four folding chairs, keeping the normal layout spacious.'),
          ('Drinks within reach', 'The compact oak drinks cabinet provides a limestone serving top, glazed cooling and concealed storage. Its restrained proportions let it serve the dining room without turning the whole room into a bar.')],
         ['6 daily / 8-10 extended', '1.16 m wide, 430 mm deep cabinet'],
         'The dining table remains at its smaller setting for ordinary use; the extended layout is for occasional gatherings.'),
    room('Arrival & living', 'The original office',
         'A dedicated work room with daylight beside the desk and a separate place to read.',
         ['office'],
         [('A useful orientation', 'The oak desk faces into the room while the bay supplies light from the side. This keeps the working position connected to the entrance without placing the monitor directly against the brightest outlook.'),
          ('Room to switch tasks', 'Closed storage contains paperwork and equipment. A reading chair offers an alternative to the desk, while the ivory walls and warm timber keep the room consistent with the original ground-floor interiors.')],
         ['1.80 x 0.80 m desk', 'Approximately 0.80 m eye-to-screen', 'Bay and original room retained'],
         'The office is a complete working room, allowing the principal-suite desk to stay a smaller personal study area.'),
    room('Arrival & living', 'The cloakroom',
         'A compact room with carefully fitted, tactile details.',
         ['cloakroom'],
         [('A floating composition', 'The shallow oak vanity and ceramic basin leave more visible floor in the narrow room. A wall-mounted bronze mixer and limestone surfaces keep the composition precise.'),
          ('Practical at a small scale', 'The drawer includes a service cut-out around the basin plumbing. The WC has a concealed cistern and visible flush plate. The retained doorway and compact shell make this a single-user room.')],
         ['1.47 x 2.42 m room', '900 x 410 mm vanity', '679 mm door opening'],
         'The earlier south window is already bricked in; this design does not add a new opening.'),
    room('Practical rooms & leisure', 'The gym',
         'Two treadmills still face the front gates, with a clearer approach from the hall.',
         ['gym'],
         [('Keep the view', 'The treadmills retain their gate-facing orientation. Their position and the gym doorway have been adjusted together to improve the entrance space. The door moves 300 mm south; the nearby window shifts 200 mm south.'),
          ('Flexible equipment', 'A bike, bench and dumbbells support different sessions, with the rower stored in two parts. Warm grey rubber flooring and oak storage bring the room into the house palette. Controls and safety lanyards are included in the model.')],
         ['Two gate-facing treadmills', 'Bike, bench and dumbbells', 'No cable tower'],
         'The activity zones are intended for different exercises; equipment clearances should not be read as all occupied at once.'),
    room('Practical rooms & leisure', 'The utility room',
         'One organised fitted run for washing, folding and household storage.',
         ['utility'],
         [('A continuous working edge', 'A 3.20 m oak run combines side-by-side laundry appliances, a folding counter and a deep sink. Two pull-out bins and tall linen and cleaning storage keep the working surface available.'),
          ('Useful small adjustments', 'The garage door is rehung within its existing opening. The sink moves 550 mm south along the same wall, keeping the service zone together while improving the arrangement around the doorway.')],
         ['3.20 m fitted run', 'Side-by-side washer and dryer', 'Deep sink and tall storage'],
         'Appliance drums, controls, bins and cabinet contents are modelled, so the utility reads as a working room.'),
    room('Practical rooms & leisure', 'Double garage and forecourt',
         'A practical garage finished with the same restraint as the house.',
         ['garage'],
         [('Two cars and useful storage', 'The model uses two 4.40 x 1.80 m concept cars within an approximately 7.71 x 6.06 m garage. Their staggered positions balance access with workbench and closed-storage space.'),
          ('A complete arrival brief', 'Four outdoor parking spaces sit on the forecourt, with a pedestrian approach to the entrance. Inside, warm grey resin flooring, ivory walls and oak fittings avoid the visual clutter of open racks.')],
         ['Two indoor car positions', 'Four outdoor parking spaces', 'Workbench and charging points'],
         'Fit depends on the chosen vehicles. With all four front car doors open, passing space narrows; one door needs to close for the shared route.'),
    room('Practical rooms & leisure', 'The cinema',
         'Four deep seats, a fixed screen and a darker, warmer atmosphere.',
         ['cinema'],
         [('A focused room', 'A single four-place sofa faces the screen, with the console below and storage behind the seating. The approximately 3.10 m viewing distance gives the screen a settled relationship to the seats.'),
          ('Comfort and circulation', 'Warm fabric and oak soften the enclosure. Entry is along the east side, where the model provides an approximately 938 mm aisle. The approach in front of the seats is tighter when people are seated.')],
         ['Four 620 mm seating places', '2.86 x 1.25 m sofa', 'Approximately 3.10 m viewing distance'],
         'The finishes establish a cinema mood; measured acoustic isolation and AV performance are not specified by this presentation.'),
    room('Practical rooms & leisure', 'The wine bar',
         'An intimate oak and limestone bar, with comfortable seating nearby.',
         ['wine-bar'],
         [('Serve and sit', 'The 2.00 m bar provides three stools, a bronze footrail and a generous working aisle behind. Cooling, bottle storage and glassware are built into the joinery.'),
          ('An evening setting', 'Paired pendants light the counter while softer illumination catches the shelving. The separate TV sofa group lets drinks and conversation continue away from the games area.')],
         ['2.00 m bar / 3 stools', 'Approximately 1.30 m serving aisle', 'Dry bar with concealed cooling'],
         'This is a dry bar: no new sink or unverified drainage route is implied.'),
    room('Practical rooms & leisure', 'The games room',
         'Pool and darts have their own places within the lower-ground leisure space.',
         ['games'],
         [('Space around the table', 'The six-foot pool table has a 1.60 x 0.83 m playing surface within an approximately 1.88 x 1.11 m overall footprint. Cue clearance is considered around the table rather than just around its legs.'),
          ('A separate throwing line', 'The dartboard and throwing position occupy a distinct zone. The retained stair and lobby continue to serve the cinema and bar, with a narrower passing strip alongside the stair guard during cue use.')],
         ['1.525 m modelled cue length', 'Dartboard bull at 1.73 m', '2.37 m throwing distance'],
         'The approximately 622 mm passing strip beside active play is a constrained route; the room is best reviewed with people and equipment in use.'),
    room('The principal suite', 'The principal bedroom',
         'A solid headboard wall, a generous bed and a calm view toward the screen.',
         ['bedroom'],
         [('The bed belongs here', 'The super-king mattress sits within a slim upholstered frame against the oak-panelled wall. Matching stone-topped bedside pieces and bronze lamps give each side a useful landing place.'),
          ('A quieter composition', 'Ivory upholstery, linen and a generous rug soften the architecture. The entrance route remains separate from the bed position, while the fixed television provides a direct view from the pillows.')],
         ['1.80 x 2.00 m mattress', '2.04 x 2.08 m bed frame', 'Two 600 mm bedside pieces'],
         'The bed and sofa televisions now share the same 85-inch screen size; neither relies on a pivoting mount.'),
    room('The principal suite', 'Sitting room and personal study',
         'Two comfortable ways to use the suite beyond the bed.',
         ['principal-sitting', 'principal-study'],
         [('A separate TV group', 'The 2.30 m sofa has its own fixed screen. Both suite televisions share a 1.882 x 1.059 m display area. The sofa screen is positioned to remain visible from the desk as well as the seats.'),
          ('A rounded L-shaped desk', 'Equal 1.80 m arms form a corner desk with 700 mm working depth. Curved inner and outer edges, rounded ends and a swivel chair allow a comfortable turn toward the room and television.')],
         ['Matching 85-inch fixed screens', 'Equal 1.80 m desk arms'],
         'The study stays open to the bedroom composition, while its side-window position gives the work surface useful daylight.'),
    room('The principal suite', 'The walk-through wardrobe',
         'Useful fitted storage without a central island to negotiate.',
         ['principal-wardrobe'],
         [('An organised passage', 'The approximately 3.79 x 3.19 m room combines a 1.90 m west run and 2.00 m south run, with 650 mm deep storage for hanging and folded clothes. An open centre keeps both runs easy to reach.'),
          ('A dressing destination', 'A 1.60 m drawer unit sits beneath the window, with a full-length mirror nearby. Oak and soft internal lighting give the wardrobe the same atmosphere as the adjoining suite.')],
         ['3.79 x 3.19 m room', '650 mm deep fitted runs', 'Window drawers and full mirror'],
         'The wardrobe moves 0.75 m toward the bed as part of the longer bathroom arrangement; the affected window moves with it.'),
    room('The principal suite', 'A more generous principal bathroom',
         'A sculptural bath, substantial stone and a dedicated window behind it.',
         ['bath'],
         [('One stone composition', 'The 1.90 x 0.90 m bath is paired with a matching limestone pedestal side table. Bronze fittings and a bath tray give the centrepiece a more complete, lavish character, with daylight through the new privacy window.'),
          ('Room for separate rituals', 'A 1.80 m double vanity, separate shower and screened WC allow the room to work beyond the bath. Extending the room by 0.75 m gives the composition more breathing space.')],
         ['1.90 x 0.90 m sculptural bath', '1.80 m double vanity', 'Approximately 1.43 x 1.70 m shower'],
         'The bath-to-shower gap is approximately 775 mm in the model. Window, structure and drainage changes need detailed design.'),
    room('Bedrooms & bathrooms', 'The garden guest bedroom',
         'A generous guest room with a super-king bed and a quiet garden outlook.',
         ['guest-bedroom'],
         [('A wall-backed arrangement', 'The bed sits against the solid east wall, with the retained rear window, radiator and balcony relationship preserved. A reading chair and modest fixed television make the room useful for a longer stay.'),
          ('Storage without swinging doors', 'A 3.675 m fitted wardrobe uses sliding fronts along the south wall. The door has been rehung within the existing opening to improve the room approach.')],
         ['1.80 x 2.00 m mattress', '650 mm deep fitted wardrobe', 'Approximately 855 mm wardrobe aisle'],
         'Using the wardrobe occupies part of the bedside aisle; the room is arranged around normal one-person access to the storage.'),
    room('Bedrooms & bathrooms', 'The guest ensuite',
         'Limestone, floating oak and bronze within the retained L-shaped room.',
         ['guest-bathroom'],
         [('Work with the shell', 'The shower remains to the south, WC to the north and floating basin along the west wall. The existing privacy window above the WC supplies daylight without moving the external opening.'),
          ('Carefully fitted details', 'The room door opens outward. The shower door opens inward to a controlled stop, keeping its swing within the enclosure. Real basin depth, clear glass and visible controls make the fittings legible.')],
         ['900 x 470 mm vanity', 'Retained L-shaped shell', 'Approximately 612 mm shower entry'],
         'This is a compact single-user ensuite; the shower entry is tight and standing zones overlap.'),
    room('Bedrooms & bathrooms', 'Bedroom 2',
         'A king bed, fitted storage and a reading corner in the original house.',
         ['bedroom2'],
         [('A solid bed wall', 'The bed uses the east wall, keeping the front window and radiator unobstructed. A warm oak headboard composition and pale upholstered frame make the bed the clear centre of the room.'),
          ('A useful perimeter', 'A two-metre wardrobe with sliding fronts sits along the west side. The north reading chair and a soft Roman blind make use of the window light without adding a desk or another screen.')],
         ['1.50 x 2.00 m king mattress', '2.00 m fitted wardrobe', '650 mm storage depth'],
         'The retained hall opening and bedside routes are compact; this is a single-file circulation arrangement.'),
    room('Bedrooms & bathrooms', 'Bedroom 3',
         'A slim king bed and a clearer route from the door to the balcony side.',
         ['bedroom3'],
         [('Keep the outlook open', 'The bed rests against the south wall, preserving the north window, radiator and existing balcony door. The upholstered frame keeps its overall width restrained.'),
          ('Storage and a small perch', 'A 2.10 m oak wardrobe provides hanging and linen storage behind sliding fronts. The luggage perch moves north to avoid crowding the entrance, giving guests a useful place to set down a bag.')],
         ['1.50 x 2.00 m king mattress', '1.66 x 2.16 m bed frame', '2.10 m fitted wardrobe'],
         'The approximately 679 mm passage beside the radiator is a compact single-file route.'),
    room('Bedrooms & bathrooms', 'Bedroom 4',
         'A compact double with useful storage and its own ensuite.',
         ['bedroom4'],
         [('A restrained footprint', 'A 1.35 m double mattress sits against the north wall in an approximately 4.10 x 3.01 m room. Shallow bedside pieces keep the bed comfortable to use without oversizing the furniture.'),
          ('Use the wall efficiently', 'The two-metre wardrobe has sliding fronts and 650 mm depth. The entrance and bathroom door positions remain in their existing openings, with their handing adjusted to improve the arrangement.')],
         ['1.35 x 1.90 m mattress', '2.00 m fitted wardrobe', 'Approximately 819 mm at the bed foot'],
         'The west bedside aisle is approximately 640 mm; the room is intentionally furnished as a compact double.'),
    room('Bedrooms & bathrooms', 'Bedroom 4 ensuite',
         'A small local partition adjustment makes a more useful shower room.',
         ['bedroom4-bath'],
         [('Make each fitting count', 'An 800 x 900 mm shower and a 900 x 400 mm vanity fit alongside the WC. A 113 mm local partition move improves the arrangement without recasting the whole bedroom.'),
          ('A consistent finish', 'Floating oak, limestone surfaces and bronze controls match the larger bathrooms. The WC stays near the north-west service area, with the retained door openings rehung for the new arrangement.')],
         ['800 x 900 mm shower', '900 x 400 mm vanity', '113 mm local partition adjustment'],
         'The former window is already bricked in. This is a compact, single-user ensuite with no new external opening.'),
    room('Bedrooms & bathrooms', 'The enlarged side bedroom',
         'A double bed with access on both sides and a clearer relationship to its bathroom.',
         ['side-bedroom'],
         [('Make room for the bed', 'The entrance partition moves north into the family-lounge approach, and the ensuite wall moves 350 mm west. This gives the bed useful space on both sides instead of trapping it against a wall.'),
          ('A complete small bedroom', 'Stone-topped bedside pieces, a 1.11 m fitted wardrobe and the retained window complete the room. The hall door opens outward to preserve the space around the bed.')],
         ['1.35 x 1.90 m mattress', 'Approximately 940 / 835 mm bedside gaps', 'Approximately 665 mm foot passage'],
         'The enlargement takes a little space from the neighbouring family area while preserving its main sitting group.'),
    room('Bedrooms & bathrooms', 'The side-bedroom ensuite',
         'A generous shower within a carefully compact room.',
         ['side-bathroom'],
         [('A clearer shower space', 'The one-metre-square shower is paired with a shallow floating vanity. Moving the shared wall helps the bedroom arrangement while keeping the bathroom fittings organised around their own use.'),
          ('Light, warm materials', 'Limestone, oak and bronze continue the house palette. The 360 mm deep vanity reduces its projection into the room, and the 800 mm bathroom opening remains part of the revised bedroom layout.')],
         ['1.00 x 1.00 m shower', '880 x 360 mm vanity', '800 mm bathroom opening'],
         'The bedroom and bathroom are designed together, rather than enlarging one without checking how the other works.'),
    room('Bedrooms & bathrooms', 'The upstairs family lounge',
         'A relaxed shared room for reading, games and the terrace outlook.',
         ['family-lounge-final'],
         [('Keep a comfortable centre', 'A 2.40 m sofa rests against the solid south wall. Nested tables and games storage create an informal family setting, with a small writing desk for occasional use.'),
          ('Leave the terrace doors free', 'The double-door swings stay clear. Shallow storage and compact furniture respect the space ceded to the enlarged side bedroom while keeping the main sitting area useful.')],
         ['2.40 m sofa', '1.14 x 0.60 m occasional desk', '375 mm deep books and games storage'],
         'In this Proposed design, the room opens onto the roof terrace; the outdoor guard and retained roof details remain visible beyond.'),
    room('Bedrooms & bathrooms', 'The family bathroom',
         'A full bath, useful vanity and a calm shared finish.',
         ['family-bathroom'],
         [('Retain the useful positions', 'The fitted bath stays in its established location, with a limestone apron and service joint. The WC sits beneath the north privacy window, and the floating vanity supplies everyday storage.'),
          ('Small details, consistent language', 'Bronze bath controls, a hand shower and restrained accessories echo the ensuites. The oak vanity softens the stone without making the room visually busy.')],
         ['1.88 x 0.78 m bath', '1.20 m vanity, 510 mm deep', 'Approximately 832 mm door opening'],
         'The fixtures share a compact room intended for one person at a time.'),
    room('Landings & lofts', 'A reading place under the stair',
         'The chair and side table now belong beneath the adjacent loft stair.',
         ['landings'],
         [('Use the sheltered edge', 'The reading chair is tucked under the stair rather than sitting out in the landing route. A small table and cordless lamp make it a complete place to pause.'),
          ('Keep the centre open', 'Warm oak flooring connects the bedroom approach, landing and stair. The reading corner uses a naturally sheltered part of the plan while leaving the main passage distinct.')],
         ['Approximately 2.03 m seated headroom', 'Approximately 2.47 m at the front', 'Chair, side table and cordless lamp'],
         'Headroom is measured at the chair position; the sloping stair underside should not be treated as uniform height.'),
    room('Landings & lofts', 'The connecting library',
         'Shallow bookshelves and concealed linen storage turn a passage into a useful part of the house.',
         ['landing-library'],
         [('Storage along the edge', 'Low-profile shelves hold books without taking over the upper gallery. A 2.10 m linen cupboard uses sliding fronts, keeping door leaves out of the circulation route.'),
          ('A continuous material thread', 'Oak floors and joinery connect the original house to the principal wing. Quiet lighting emphasises the storage and wall surfaces rather than adding loose furniture to the passage.')],
         ['2.10 m linen cupboard', 'Sliding fronts', 'Shallow library shelving'],
         'Stairs and guards remain part of the retained route; the storage is arranged around them.'),
    room('Landings & lofts', 'The loft bedroom',
         'A separate king-bedroom suite above the principal room.',
         ['loft-bedroom'],
         [('Use the dormer volume', 'The bed sits against a solid wall within the dormer, with a slim frame and deliberately shallow bedside pieces. The bedroom and bathroom doors are rehung on the east jambs of their existing openings.'),
          ('A cleaner edge', 'The low hip-store shelves and their contents have been removed. A retained fitted wardrobe supplies the main storage, while the lower eaves remain visually quiet and separate from the standing area.')],
         ['1.50 x 2.00 m king mattress', '1.97 m wardrobe, 580 mm deep', 'Approximately 2.09 m structural headroom'],
         'Headroom reduces with finishes and roof slopes. The low eaves are not full-height usable floor area.'),
    room('Landings & lofts', 'The loft ensuite',
         'A complete shower room tucked into the upper suite.',
         ['loft-bathroom'],
         [('A simple sequence', 'A floating vanity, separate shower and concealed-cistern WC make the room legible at a glance. Their footprints fit the retained loft enclosure rather than assuming a rectangular full-height room.'),
          ('Warmth in a small space', 'Ivory walls and limestone are balanced by oak drawers and bronze fittings. Clear glass keeps the shower visually open, with practical controls and basin depth included in the model.')],
         ['1.00 m vanity, 470 mm deep', 'Approximately 1.09 x 1.10 m shower', 'Concealed-cistern WC'],
         'The roof profile and door swing remain important when judging the standing space around each fitting.'),
    room('Landings & lofts', 'The loft hobby room',
         'A flexible making and project space over the original house.',
         ['hobby'],
         [('A table that can move', 'The two-person project table sits on lockable castors so the room can change between hobbies. Sliding supply storage, a low archive and bookshelves support longer projects without filling the centre.'),
          ('Work with the roof', 'Existing slopes, beams, windows and stairs are retained. Oak flooring ties the room to the rest of the house, while the low storage uses the eaves as occasional access space.')],
         ['2.00 x 1.05 m project table', 'Lockable castors', 'Low archive and sliding supply storage'],
         'Eaves storage is reached by stooping; it does not create additional full-height working space.'),
    room('Landings & lofts', 'The loft sitting area and bridge',
         'An informal place to relax beside the project space.',
         ['loft-lounge'],
         [('More than a work room', 'A sofa, reading chair and small tables make the loft useful between projects. Low furniture respects the sloping roof and leaves the central route open.'),
          ('The unresolved connection', 'The bridge between the loft areas has approximately 1.78-1.90 m clear headroom, with a recorded minimum near 1.783 m. This remains a design constraint to resolve with architectural and structural input.')],
         ['Sofa and separate reading chair', 'Retained loft route and guard', 'Bridge headroom remains constrained'],
         'The attractive room view does not remove the bridge headroom issue; this connection needs further design review.'),
    room('Terrace & garden', 'The roof terrace',
         'A relaxed sitting group and a separate cafe table above the garden.',
         ['roof-terrace', 'roof-dining'],
         [('A place to lounge', 'A two-seat sofa and two chairs gather around a stone coffee table. Pale timber and ivory cushions continue the interior palette, with furniture set back from the retained guards.'),
          ('A place to eat outside', 'A 1.05 m round table provides four seats. The three flush rooflights, door approach, privacy screen and drainage remain part of the terrace arrangement; no canopy or enclosure is added.')],
         ['Approximately 9.35 x 5.07 m terrace', 'Three 1.00 m square rooflights'],
         'This furniture arrangement is not a verification of roof loading, guarding, wind resistance or waterproofing details.'),
    room('Terrace & garden', 'The pool garden',
         'The brick house, water and pale stone terrace form one garden composition.',
         ['pool-brick'],
         [('The outdoor centre', 'An 8.00 x 3.50 m pool and sunken spa anchor the garden leisure area. The raised terrace links the water to the pavilion seating and garden buildings.'),
          ('A considered perimeter', 'The current model keeps three loungers along the west deck, rotated as requested, with clear strips beside the pool. Pale outdoor timber, ivory upholstery and stone tables carry the house palette outside.')],
         ['8.00 x 3.50 m pool', 'Sunken spa', 'Three loungers in the current model'],
         'House walls use the selected brick finish. Dormer faces and cheeks remain tiled, including in the garden view.'),
    room('Terrace & garden', 'The pool pavilion',
         'A comfortable sheltered edge beside the water.',
         ['pool-pavilion'],
         [('Sit between swims', 'A 2.20 m sofa and stone table provide a proper sitting place beyond the loungers. Towel storage and restrained planting make the area useful without crowding the pool circulation.'),
          ('Connect the levels', 'Two 172 mm steps with 370 mm treads lead to the retained raised garden building. The change in level remains visible and should be considered as part of the whole pool route.')],
         ['2.20 m outdoor sofa', 'Two steps to the garden building', 'Ivory upholstery and pale timber'],
         'The pavilion, pool and changing spaces work as one sequence; the raised garden-building access is not step-free.'),
    room('Terrace & garden', 'Summer house and changing room',
         'A small garden retreat, with a useful private corner for changing.',
         ['garden-house', 'garden-changing'],
         [('A place for two', 'The retained 1.76 x 3.78 m shell accommodates a compact two-person bench and shallow drinks cupboard. The small scale keeps the summer house intimate and usable.'),
          ('A simple changing space', 'A bench, hooks and curtain form the changing corner at the north end. The raised floor and existing shell remain, with materials coordinated with the pool seating outside.')],
         ['1.56 x 0.63 m two-person bench', 'Changing bench, curtain and hooks'],
         'The garden building is carefully fitted within its retained narrow footprint; no larger pavilion is implied by the presentation.'),
    room('Terrace & garden', 'Garden WC and tool store',
         'Small support spaces that help the garden work as a complete area.',
         ['garden-wc', 'garden-tools'],
         [('A garden washroom', 'The 1.80 x 1.57 m WC includes a 640 mm basin, floating pan and bronze fittings. Ivory and stone surfaces keep it visually connected to the house bathrooms.'),
          ('A shallow, useful store', 'The adjacent 1.80 x 0.91 m tool store uses a 230 mm rack and wall hooks. It is sized for garden equipment storage rather than a second workbench.')],
         ['Separate WC and tool-store doors', 'Retained raised garden-building floor'],
         'Both outward-opening doors and the level change remain important parts of the approach.'),
    room('Terrace & garden', 'The garden workshop',
         'A bright working room with clear floor space and generous making surfaces.',
         ['workshop'],
         [('Work along the window wall', 'The long oak bench sits beneath the north windows, with sliding storage on the west side. Daylight falls across the working surface and the centre stays available for larger projects.'),
          ('Move the project, keep the route', 'A mobile 1.60 x 0.80 m assembly table supports different tasks. Light oak, ivory and grey metal keep the room calm. The existing east entrance and window positions are retained.')],
         ['Approximately 6.21 x 4.12 m room', '2.40 m clear height', '900 mm high working bench'],
         'The workshop approach stepping stones have been removed from the current model; the retained garden route serves the entrance.'),
    dict(kind='palette', chapter='Details & review', title='One palette, many moods', images=['kitchen-sink','original-stair','bath','front-brick']),
    dict(kind='review', chapter='Details & review', title='Review the house as a whole', images=[]),
]

assert len(PAGES) == 50, len(PAGES)

IMAGE_LABELS = {
    'front-brick': 'Brick facade and arrival', 'arrival': 'Entrance gallery',
    'original-stair': 'Original staircase', 'kitchen': 'Kitchen and garden dining',
    'kitchen-oven': 'Oven controls and appliance wall', 'kitchen-sink': 'Sink, bronze tap and limestone counter',
    'tv-lounge': 'TV lounge', 'formal-lounge-final': 'Formal lounge', 'formal': 'Formal dining',
    'drinks': 'Formal dining drinks cabinet', 'office': 'Original ground-floor office',
    'cloakroom': 'Cloakroom', 'gym': 'Gym facing the front gates', 'utility': 'Utility room',
    'garage': 'Double garage', 'cinema': 'Cinema', 'wine-bar': 'Wine bar', 'games': 'Games room',
    'bedroom': 'Principal bedroom', 'principal-sitting': 'Principal sofa and fixed TV',
    'principal-study': 'Principal L-shaped desk', 'principal-wardrobe': 'Walk-through wardrobe',
    'bath': 'Principal bathroom', 'guest-bedroom': 'Garden guest bedroom',
    'guest-bathroom': 'Guest ensuite', 'bedroom2': 'Bedroom 2', 'bedroom3': 'Bedroom 3',
    'bedroom4': 'Bedroom 4', 'bedroom4-bath': 'Bedroom 4 ensuite',
    'side-bedroom': 'Enlarged side bedroom', 'side-bathroom': 'Side-bedroom ensuite',
    'family-lounge-final': 'Upstairs family lounge', 'family-bathroom': 'Family bathroom',
    'landings': 'Reading corner under the loft stair', 'landing-library': 'Connecting library and linen storage',
    'loft-bedroom': 'Loft bedroom above the principal suite', 'loft-bathroom': 'Loft ensuite',
    'hobby': 'Original-house loft hobby room', 'loft-lounge': 'Loft sitting area',
    'roof-terrace': 'Roof terrace lounge', 'roof-dining': 'Roof terrace dining',
    'pool-brick': 'Pool garden and brick house', 'pool-pavilion': 'Pool pavilion seating',
    'garden-house': 'Summer house', 'garden-changing': 'Garden changing area',
    'garden-wc': 'Garden WC', 'garden-tools': 'Garden tool store', 'workshop': 'Garden workshop',
}

assert len(IMAGE_LABELS) == 48
assert {key for page in PAGES for key in page['images']} == set(IMAGE_LABELS)
