"""Room groups and spatial reading notes; geometry comes from the current export."""
def area(key,title,after,z,rooms,zones,movement,check):
    return dict(key=key,title=title,after=after,z=z,rooms=rooms,zones=zones,movement=movement,check=check)

AREAS=[
 area('arrival','Entrance and original hall',9,0,['New entrance gallery','Attached entrance gallery','Entrance hall'],
      [('Arrive','coat|key return','Shallow storage follows the entrance corner.'),('Pause','shoe bench','The bench gives shoes and bags a home beside the door.'),('Connect','tread|winder','The original stair and gallery lead into the living rooms.')],
      'Follow the entrance gallery into the original hall. The coat cabinet sits on the edge of that route, not across its centre.',
      '320 mm cabinet depth; the original stair position and openings are retained.'),
 area('kitchen','Kitchen and garden dining',11,0,['Kitchen','Garden living and dining'],
      [('Prepare','island.*top|island.*counter','The island anchors the preparation and gathering zone.'),('Cook','oven','Tall appliances sit close to the working run.'),('Dine','dining.*table|table.*top','The everyday dining table takes the garden light.')],
      'The kitchen sits between the hall, garden dining and TV lounge. Read the furniture footprints together with the door openings, rather than treating the island as a free-standing sculpture.',
      'The accepted kitchen arrangement is retained. Small fittings are omitted from the plan for clarity.'),
 area('tv-lounge','TV lounge',12,0,['Side garden living'],
      [('Watch','sofa.*seat|sofa.*base','The curved sofa has a fixed screen on a solid wall.'),('Set down','coffee.*top|coffee table','Tables sit within reach of the seating.'),('Store','media.*console','Low media joinery supports the screen composition.')],
      'Keep the route between kitchen and garden at the edge of the sitting group. The sofa and screen form a settled pair.',
      'The secondary garden-side seats are part of the same open living area.'),
 area('formal','Formal lounge and dining',14,0,['Formal dining and lounge'],
      [('Converse','sofa.*seat|sofa.*base','Two facing sofas create a conversation group.'),('Dine','dining.*table|table.*top','Six everyday places; the table extends for occasions.'),('Serve','drinks.*counter|drinks.*cabinet','The shallow drinks cabinet serves the dining end.')],
      'The room works as two linked groups. Doors, fireplace and bay set the edges; the dining table stays at its smaller setting in ordinary use.',
      '1.80 x 1.00 m table extends to 2.80 m. Occupied chairs temporarily need more space than their stored footprints.'),
 area('office','Original office',15,0,['Office'],
      [('Work','desk.*top','The desk faces into the room with light from the bay.'),('Read','chair.*seat','A separate chair supports reading away from the monitor.'),('Organise','cabinet|storage','Closed storage keeps the desk surface available.')],
      'Enter into the side of the working arrangement, with the bay remaining a source of daylight rather than a blocked wall.',
      '1.80 x 0.80 m desk. Chair movement uses more space than the chair footprint alone.'),
 area('cloakroom','Cloakroom',16,0,['Cloakroom'],
      [('Wash','vanity|basin','A shallow floating vanity keeps the room open.'),('WC','WC.*pan|toilet.*pan','The concealed cistern stays against the service wall.'),('Enter','door.*leaf','The retained opening fixes the approach.')],
      'This is a compact single-user room. Door movement and the standing position in front of the basin share a small floor area.',
      '900 x 410 mm vanity; approximately 679 mm door aperture.'),
 area('gym','Gym',17,0,['Gym'],
      [('Cardio','treadmill.*running|treadmill.*chassis','Both treadmills face the gate side.'),('Cycle','bike','The bike has a separate activity position.'),('Strength','bench|dumbbell','Bench and weights support a different session.')],
      'The doorway moves south to improve arrival around the treadmills. The rower is stored in two parts; exercise zones are not all occupied at the same time.',
      'Keep the two treadmill rear safety zones clear. Use the room study for the occupied exercise arrangements.'),
 area('utility','Utility room',18,0,['Utility'],
      [('Wash','washing|washer|dryer','Laundry appliances sit side by side.'),('Fold','counter|worktop','A continuous worktop supports sorting and folding.'),('Store','tall.*cabinet|linen','Tall storage holds linen and household equipment.')],
      'The working run stays on one side, with the garage door rehung inside its existing opening. The aisle remains the main organising space.',
      '3.20 m fitted run. Open appliance doors and drawers occupy the aisle temporarily.'),
 area('garage','Double garage',19,0,['New double garage'],
      [('Park','car.*body|car.*shell','Two concept cars sit in staggered positions.'),('Work','honed stone worktop','A useful bench belongs to the garage perimeter.'),('Store','tall cupboard shelf','Closed storage keeps loose equipment contained.')],
      'The forecourt adds four outdoor positions. Within the garage, vehicle size and door opening matter as much as the static parking rectangles.',
      'Model cars are 4.40 x 1.80 m. Closing one front door restores a passing route when the other doors are open.'),
 area('cinema','Cinema',20,-2.8,['Basement cinema'],
      [('Sit','seat.*cushion|sofa|cinema.*seat','Four deep places form one viewing row.'),('Watch','screen','The screen remains fixed ahead of the seats.'),('Store','storage|cabinet','Storage uses the rear of the room.')],
      'Enter along the side of the seating group. The front approach is more restricted when viewers are seated with their legs extended.',
      'Approximately 938 mm side aisle and 3.10 m viewing distance.'),
 area('bar','Wine bar, media and games',22,-2.8,['Basement bar and games room'],
      [('Serve','bar limestone top','A three-stool social counter has a separate serving aisle.'),('Play','pool playing cloth','The pool table retains its six-foot proportions and cue zone.'),('Relax','media seat','A fixed TV and sofa create an independent sitting group.')],
      'The L-shaped room separates drinks, pool and sofa use. The dartboard and throwing line sit along the east side; keep the line of play clear.',
      'The decor refinement adds shallow wall treatments, artwork and lighting. It does not enlarge the room or reduce the need for cue clearance.'),
 area('principal','Principal bedroom, sitting and study',24,2.8,['New principal suite','Principal window alcove'],
      [('Sleep','mattress','The super-king bed is backed by a solid wall.'),('Watch','sofa.*seat|sofa.*base','The sofa has a separate fixed screen of the same size.'),('Work','desk.*top','Equal desk arms form a rounded L-shaped workspace.')],
      'The route from the wardrobe arrives beside the main furniture groups. Bed, sofa and desk each have a clear use without turning the bed into an obstruction.',
      '1.80 x 2.00 m mattress; 2.30 m sofa; 1.80 m desk arms; matching 85-inch screens.'),
 area('dressing-bath','Walk-through wardrobe and bathroom',26,2.8,['New dressing room','New principal bathroom'],
      [('Dress','wardrobe','Fitted hanging, shelves and drawers line the room edges.'),('Bathe','bath hollow|freestanding bath','The sculptural bath is placed by the new privacy window.'),('Wash','vanity.*counter|basin','A double vanity and separate shower complete the suite.')],
      'The longer bathroom and shifted wardrobe work as one adjustment. Both affected windows move 0.75 m toward the bedroom.',
      'Approximately 775 mm bath-to-shower gap. The measured plan is a model study, not a drainage or structural design.'),
 area('guest','Garden guest bedroom and ensuite',28,2.8,['Garden guest suite','Garden guest en suite'],
      [('Sleep','mattress','A super-king bed sits on the solid east wall.'),('Store','wardrobe','Sliding storage lines the room without door swings.'),('Bathe','vanity|shower','The L-shaped ensuite retains its external window.')],
      'The rear window and balcony relationship are retained. Storage use temporarily occupies a bedside aisle; the bathroom is arranged for one person.',
      'Approximately 855 mm wardrobe aisle and 612 mm net shower entry.'),
 area('bedroom2','Bedroom 2',29,2.8,['Bedroom 2'],
      [('Sleep','mattress','The king bed uses the solid east wall.'),('Store','wardrobe','Sliding wardrobe fronts keep swings out of the route.'),('Read','chair.*seat','The reading chair sits beside useful daylight.')],
      'The front window and radiator stay open to the room. Furniture is concentrated along the solid walls to preserve the centre.',
      '1.50 x 2.00 m mattress; 2.00 m wardrobe with 650 mm depth. Bedside routes remain single-file.'),
 area('bedroom3','Bedroom 3',30,2.8,['Bedroom 3'],
      [('Sleep','mattress','The bed rests against the south wall.'),('Store','wardrobe','Fitted storage occupies the west side.'),('Arrive','perch|bench','A moved luggage perch clears the entry.')],
      'Preserve the route to the retained balcony door and north window. The compact bed frame avoids consuming extra passage space.',
      '1.50 x 2.00 m mattress; approximately 679 mm beside the radiator.'),
 area('bedroom4','Bedroom 4 and ensuite',32,2.8,['Bedroom 4','Bedroom 4 en suite'],
      [('Sleep','mattress','A double bed gives the compact room a clear centre.'),('Store','wardrobe','A two-metre sliding wardrobe supplies useful storage.'),('Bathe','vanity|shower','The ensuite uses a small local partition adjustment.')],
      'Both door apertures remain, with the leaves rehung. The bathroom and bedroom are assessed together because their approaches share the same corner.',
      '1.35 x 1.90 m mattress; 800 x 900 mm shower; approximately 640 mm west bedside aisle.'),
 area('sidebed','Side bedroom and ensuite',34,2.8,['Side wing south bedroom','Side south ensuite'],
      [('Sleep','mattress','The double bed now has usable space on both sides.'),('Store','wardrobe','Compact fitted storage stays beside the entrance.'),('Bathe','shower|vanity','A one-metre shower and shallow vanity form the ensuite.')],
      'The bedroom entrance moves north into the family approach; the ensuite wall moves 350 mm west. The plan shows the whole revised pair.',
      'Approximately 940 / 835 mm bedside spaces and 665 mm bed-foot passage.'),
 area('family','Upstairs family lounge',35,2.8,['Upstairs family lounge'],
      [('Sit','sofa.*seat|sofa.*base','The sofa fits the solid south wall.'),('Write','desk.*top','A compact occasional desk uses the window edge.'),('Play','chess|coffee.*top','Games and nested tables support informal family use.')],
      'The terrace doors remain free to open. Shallow storage respects the space taken into the enlarged side bedroom.',
      '2.40 m sofa; 1.14 x 0.60 m desk; 375 mm deep storage.'),
 area('familybath','Family bathroom',36,2.8,['Bathroom'],
      [('Bathe','bath','The fitted bath keeps its established position.'),('Wash','vanity|basin','The floating vanity supplies shared storage.'),('WC','WC.*pan|toilet.*pan','The WC sits below the privacy window.')],
      'The compact room is for one person at a time. Leave the entry and standing positions clear of loose accessories.',
      '1.88 x 0.78 m bath; 1.20 m vanity, 510 mm deep.'),
 area('landings','Upper landings and library',38,2.8,['Landing','Joined first-floor landing','Landing library','New upper gallery','Side-wing connecting landing'],
      [('Read','reading chair.*seat','The chair sits underneath the adjacent stair.'),('Browse','bookcase shelf','Shallow bookshelves use the gallery edge.'),('Store','linen','Sliding linen storage avoids opening into the passage.')],
      'The landing is primarily a route between bedrooms and stairs. Useful storage and a single sheltered seat occupy its edges.',
      'Reading-seat headroom is approximately 2.03 m, increasing to 2.47 m in front.'),
 area('loftsuite','Loft bedroom and ensuite',40,5.55,['New loft bedroom','Loft ensuite'],
      [('Sleep','mattress','The king bed uses the solid dormer wall.'),('Store','wardrobe','The retained entrance wardrobe supplies storage.'),('Bathe','shower|vanity','A compact ensuite sits at the end of the suite.')],
      'The doors are rehung within their existing openings. The low hip-store shelves and cupboards have been removed from the bedroom edge.',
      'Approximately 2.09 m structural dormer headroom before finishes; low eaves are not standing space.'),
 area('hobby','Original-house loft hobby room',42,5.55,['Loft studio and lounge','Loft east eaves store','Loft west eaves store'],
      [('Make','project.*top|table.*top','A mobile table supports two-person projects.'),('Relax','sofa.*seat|sofa.*base','A small lounge occupies the quieter end.'),('Organise','archive|storage','Low storage uses the eaves for occasional access.')],
      'The middle stays available for moving projects and reaching both ends. Low eaves storage is accessed by stooping.',
      'The separate bridge has only approximately 1.78-1.90 m headroom and remains unresolved.'),
 area('terrace','Roof terrace',43,2.8,['Shared roof terrace'],
      [('Lounge','sofa.*seat|sofa.*base','A sofa and two chairs form the relaxed group.'),('Dine','dining.*top|cafe.*top|table.*top','A separate round table provides four seats.'),('Keep clear','walk-on lantern.*glass','Three rooflights remain visible and unobstructed.')],
      'Move between the door, lounge and table without crossing rooflights. Furniture stays back from the retained guard and privacy screen.',
      'Terrace footprint is approximately 9.35 x 5.07 m. Loading, guarding and waterproofing need detailed design.'),
 area('poolgarden','Pool, spa and pavilion',45,.2,['Pool terrace','Expanded garden pavilion','Pool hot tub area'],
      [('Swim','pool water','The rectangular pool anchors the outdoor area.'),('Rest','lounger.*seat|lounger.*cushion','Three loungers stay in their revised orientation.'),('Gather','sofa.*seat|sofa.*base','The pavilion offers a separate shaded sitting group.')],
      'The deck connects pool, spa, loungers and pavilion. Steps lead up to the retained garden building rather than providing level access.',
      '8.00 x 3.50 m pool; approximately 950 mm west clear strip and 1.14 m east aisle in the model.'),
 area('gardenhouse','Summer house, changing and stores',47,.5445870161,['Summer house','Outside WC','Tool store'],
      [('Sit and change','summer.*seat|changing.*bench','The narrow summer house includes a changing corner.'),('Wash','basin|WC.*pan','The outside WC has its own outward-opening door.'),('Store','tool.*shelf','Shallow shelving holds garden tools.')],
      'Three small retained shells support the pool garden. Door swings and the raised floor are part of the approach.',
      'Summer house approximately 1.76 x 3.78 m; WC 1.80 x 1.57 m; tool store 1.80 x 0.91 m.'),
 area('workshop','Garden workshop',48,-.4594424708,['Garden workshop'],
      [('Make','assembly.*top|table.*top','The mobile assembly table keeps the centre adaptable.'),('Work','workbench|bench.*top','A long working surface sits under the windows.'),('Store','storage|cupboard','Closed storage uses the west wall.')],
      'The east entrance remains clear, with the main working surfaces along the window wall. The garden strip route replaces the removed stepping stones.',
      'Approximately 6.21 x 4.12 m room, 2.40 m clear height and a 1.60 x 0.80 m mobile table.'),
]
assert len(AREAS)==27
