"""Reuse the established isolated-room controls for the developed leisure rooms."""
import json,shutil
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];PUBLIC=ROOT/'walkthrough/public/interiors/leisure';PUBLIC.mkdir(parents=True,exist_ok=True)
rooms={
 'guest':{'title':'Garden guest bedroom','headline':'A restful room with a garden outlook.','intro':'A wall-backed super-king bed, useful fitted storage and a quiet place to read.','fullRoom':'2445673-0','plan':'layout-plan.svg','copy':[
  ('A settled place for the bed.','The bed sits against the solid east wall, with an upholstered headboard, floating oak bedsides and individual reading lights. A fixed 43-inch television fits the short wall between the doorways. Full-height ivory curtains, warm wool carpet and a curved reading chair soften the retained room.'),
  ('Storage without blocking the view.','A 3.675 m fitted wardrobe runs along the south wall, using sliding fronts to keep the aisle free. It replaces the previous 4.24 m run. The window and radiator stay clear, and the reading table sits back from the route around the bed.'),
  ('The measured trade-offs.','The wardrobe-to-bed aisle is 855 mm. Someone choosing clothes occupies that side while the other bedside, ensuite and balcony remain reachable. The fixed television has a modest image size at this distance. The ensuite door opens into the bedroom to release space in the compact bathroom; the existing doorway stays in place.') ]},
 'guestbath':{'title':'Guest ensuite','headline':'A compact bathroom, carefully fitted.','intro':'A floating oak basin unit, limestone shower and restrained bronze fittings.','fullRoom':'2445675-0','plan':'layout-plan.svg','copy':[
  ('Keep the useful arrangement.','The shower stays in the south recess, the WC below the north window and the basin along the west service wall. A 900 mm floating oak unit, recessed ceramic basin and lit mirror create a cleaner room. The existing window remains; a simple linen blind replaces the heavy curtains.'),
  ('Make the door movements work.','The bedroom door opens outward. The shower door opens inward to an 85-degree stop, with its double-sided handle clear of the wall and room to stand inside while closing it. The shower controls are on the back wall, away from the moving glass.'),
  ('A small, single-user room.','The shower entry is approximately 612 mm wide and remains tight. The basin and WC share standing space. The layout checks these uses separately and tests a 600 mm body through the shower. This is a developed concept: the actual enclosure, opening stop, waterproofing and services need selection against measured site dimensions.') ]},
 'utility':{'title':'Utility','headline':'A calm, practical laundry.','intro':'One fitted oak run, a generous clear aisle and a useful place to fold.','fullRoom':'proposal-utility','plan':'layout-plan.svg','copy':[
  ('Everything in a useful sequence.','The washer and dryer face into the room beneath a shared folding surface. A pull-out laundry hamper, undermount sink and tall storage complete the run. Oak, limestone, ivory appliance fronts and bronze details continue the house palette. The existing window brings light above the worktop.'),
  ('Small changes, better movement.','The room retains its walls, window and both door openings. The garage door is rehung on the other jamb so its open leaf stays away from the working area. The sink remains on the east service wall with a local position adjustment. There is no WC.'),
  ('Checked in use.','The aisle measures 1.595 m to the worktop. Open appliance doors, the pulled-out hamper, folding and sink use have each been checked with a 600 mm navigation body and the room doors open. These are separate working states. Final appliance dimensions, service connections and the garage door specification still need detailed selection.') ]},
 'gym':{'title':'Gym','headline':'Space to train, room to move.','intro':'Two west-facing treadmills, a clear strength area and useful oak storage.','fullRoom':'proposal-gym','plan':'layout-plan.svg','copy':[
  ('A calmer training room.','Warm grey rubber, natural oak and ivory carry the house palette into the gym. A full-size dumbbell bench, eight pairs of weights, a compact cable tower and west-facing bike have their own places. Towels, water and a rolled mat are gathered beside the utility. The windows remain clear and the room has no mirror.'),
  ('Two exercise modes.','Both treadmills have a clear two-metre run-off behind them. The rower is stored in two parts in the default model. For rowing, both treadmills are switched off and the marked rear floor area is used instead. The bench stays in place. The measured plan shows these distinct arrangements.'),
  ('The practical limits.','The eastern passage beside the running area is approximately 640 mm wide, so it is single-file. Running, rowing, cycling, cable work and bench exercises have been checked as separate activities; this is not a claim that every station can operate together. The previous barbell rack and loose ball have been removed to improve access. Final equipment, selected exercises, fixings, floor loads and ventilation require detailed review.') ]},
 'cinema':{'title':'Cinema','headline':'A quieter place to watch.','intro':'Deep seats, warm fabric and oak, with a clear view from every place.','fullRoom':'proposal-basement-cinema','plan':'arrangements.svg','copy':[
  ('One comfortable row.','Four generous fixed seats face a 2.6 m screen. A low limestone table leaves a 650 mm approach to the seats; the wider eastern aisle leads back to the door. Cup holders and charging are built into the centre console, with shallow storage for blankets behind the sofa.'),
  ('An explicit trade-off.','This arrangement has four places, compared with six in the previous two-row layout. It removes the rear platform and keeps other viewers out of the screen sightline. The seat approach is single-file and passing in front of occupied knees still requires people to tuck in. The fabric, oak divisions and low lighting soften the room; sound isolation, ventilation and final equipment remain to be designed.') ]},
 'bar':{'title':'Wine bar & games','headline':'Room to serve, sit and play.','intro':'A fitted oak and limestone bar, a comfortable TV group and separate spaces for pool and darts.','fullRoom':'proposal-basement-bar','plan':'layout-plan.svg','copy':[
  ('A usable serving space.','The two-metre bar keeps three places, with upholstered stools, a bronze footrail and a proper knee overhang. Behind it, a 1.3 m clear working aisle gives access to the wine cooler, drinks cooler, drawers and glass storage. This is a dry bar; glass washing stays in the utility or kitchen.'),
  ('Each activity has its own place.','A standard 6-foot British pool table turns across the room, with full-length cue space around the playing surface. The darts zone sits separately between the pool and bar, away from the cinema route. The west-facing sofa has its own fixed TV and controller table.'),
  ('The space that remains tight.','With the full pool-playing area reserved, the passing strip beside the stairs is about 620 mm wide. It works as single-file access, not a broad principal route. The measured plan shows this alongside occupied stools and the separate darts area. Equipment selection, delivery, acoustics and ventilation still need detailed review.') ]}
}
labels={'entrance':'From the doorway','seated':'From the sofa','left-seat':'Left cinema seat','right-seat':'Right cinema seat','reverse':'Looking back','details':'Fittings & details','overview':'Cutaway overview','bar':'At the bar','serving':'Serving aisle','games':'Pool & games','sofa':'TV from the sofa','darts':'Darts area','cardio':'Cardio area','strength':'Strength area','water':'Towels & water','laundry':'Laundry & folding','sink':'At the sink','bed':'From the bed','garden':'Reading corner','wardrobe':'Wardrobe wall','vanity':'At the basin','shower':'The shower','window':'Window & WC'}
style='''.model-area{position:relative;height:70vh;min-height:360px;background:#dfdfd5;overflow:hidden;border-radius:6px}.model-area canvas{display:block;width:100%;height:100%;touch-action:none}.model-tools{display:flex;gap:7px;flex-wrap:wrap;margin-bottom:16px}.model-tools button[aria-pressed=true]{color:white;background:var(--green)}.model-status{position:absolute;inset:0;background:#e5e4daed;display:grid;place-items:center}.model-caption{font-size:12px;color:var(--muted);line-height:1.7}.room-copy{max-width:900px;line-height:1.7}.room-copy h2{margin-top:28px}.room-nav{display:flex;gap:20px;flex-wrap:wrap;padding:0 0 24px}.room-nav a[aria-current=page]{font-weight:700}.plan{width:100%;display:block;margin-top:30px}.cards{display:grid;grid-template-columns:1fr 1fr;gap:24px;margin:30px 0}.card{padding:28px;border:1px solid #d1d5c7;background:#eeeee5;border-radius:8px}.card h2{margin-top:0}@media(max-width:720px){.model-area{height:62vh}.model-tools button{font-size:11px;padding:8px 11px}.cards{grid-template-columns:1fr}}'''
header='<header><a class="brand" href="../../">⌂ <span>Ashley Heights<small>INTERIOR DESIGN STUDIO</small></span></a><a id="full-house" href="../../?design=proposed">Full house ↗</a></header>'
def head(title):return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+title+' · Ashley Heights</title><link rel="icon" href="data:,"><link rel="stylesheet" href="studio.css"><style>'+style+'</style></head><body>'+header
for stem,r in rooms.items():
 meta=json.loads((PUBLIC/'models'/('compact-'+stem+'.json')).read_text());config={'modelStem':stem,'fullHouseRoom':r['fullRoom'],'planAsset':stem+'-plan.svg','maxDistance':25,'noGarden':True,'views':meta['views']}
 shutil.copyfile(ROOT/'revisions/interiors-overnight-2026-09-27'/stem/r['plan'],PUBLIC/(stem+'-plan.svg'))
 buttons=''.join(f'<button data-camera="{key}" aria-pressed="{str(key=="entrance").lower()}">{labels[key]}</button>'for key in config['views'])
 nav='<nav class="room-nav" aria-label="Room studies">'+''.join(f'<a href="{s}.html" data-study="{s}.html"'+(' aria-current="page"'if s==stem else'')+'>'+rr['title']+'</a>'for s,rr in rooms.items())+'</nav>'
 copy=''.join('<h2>'+title+'</h2><p>'+body+'</p>'for title,body in r['copy'])
 html=head(r['title'])+'<main>'+nav+'<section class="intro"><div><p class="eyebrow">'+r['title'].upper()+' / ROOM DEVELOPMENT 01</p><h1>'+r['headline']+'</h1><p>'+r['intro']+'</p></div><label class="design-label">Viewing design<select id="model-design"><option value="compact">Proposed</option><option value="planning">Proposed · planning application</option></select></label></section><nav class="model-tools" aria-label="Room views">'+buttons+'<button id="reset-model">Reset view</button></nav><div class="model-area"><canvas id="room-model" aria-label="Interactive 3D room. Drag to orbit, scroll to zoom, right-drag to pan."></canvas><div id="model-status" class="model-status" role="status">Loading your room…</div></div><p class="model-caption">Drag to look around · scroll to zoom · right-drag to pan. The ceiling is removed only in the cutaway.</p><div class="room-copy">'+copy+'</div><img id="layout-plan" class="plan" alt="Measured room arrangement and activity clearances"><p class="model-caption">Developed concept for review. Dimensions come from the model. Furniture access, viewing and simultaneous-use checks are recorded separately from construction feasibility.</p></main><footer>Ashley Heights · '+r['title']+' / 01</footer><script>window.INTERIOR_PREVIEW_CONFIG='+json.dumps(config)+';document.querySelectorAll("[data-study]").forEach(a=>a.href=a.dataset.study+"?design="+(new URLSearchParams(location.search).get("design")==="planning"?"planning":"compact"));</script><script type="module" src="room-model.js"></script></body></html>'
 (PUBLIC/(stem+'.html')).write_text(html)
cards=''.join('<a class="card" href="'+s+'.html"><h2>'+r['title']+'</h2><p>'+r['intro']+'</p><span>Explore the room →</span></a>'for s,r in rooms.items())
(PUBLIC/'index.html').write_text(head('Room studies')+'<main><section class="intro"><div><p class="eyebrow">ROOM DEVELOPMENT</p><h1>The next rooms, thoughtfully arranged.</h1><p>Warm oak, limestone and ivory carry through the house, with darker finishes around the cinema screen.</p></div></section><div class="cards">'+cards+'</div><p><a href="../principal/bedroom.html">Principal suite ↗</a> · <a href="../kitchen/model.html">Kitchen &amp; TV lounge ↗</a></p></main><footer>Ashley Heights · Interior design studio</footer></body></html>')
print('Built leisure room review pages')
