#!/usr/bin/env python3
"""Build selected designs concurrently, reusing verified completed models."""
import argparse
from concurrent.futures import ThreadPoolExecutor, as_completed
from contextlib import contextmanager, ExitStack
import fcntl
import os
from pathlib import Path
import subprocess

if __package__:
    from .build_support import Timings, current_build
else:
    from build_support import Timings, current_build

ROOT = Path(__file__).resolve().parents[1]


def run(args, env=None, cwd=None, log=None):
    print('RUN', ' '.join(map(str, args)), flush=True)
    subprocess.run(list(map(str, args)), cwd=cwd or ROOT, env=env, check=True,
                   stdout=log, stderr=subprocess.STDOUT if log else None)


@contextmanager
def selected_build_lock(variants):
    """Reject an overlapping runner before checking or replacing its outputs."""
    with ExitStack() as stack:
        for variant in sorted(variants):
            path = ROOT / ('output-proposed-' + variant) / '.runner.lock'
            path.parent.mkdir(parents=True, exist_ok=True)
            handle = stack.enter_context(path.open('a+'))
            try:
                fcntl.flock(handle, fcntl.LOCK_EX | fcntl.LOCK_NB)
            except BlockingIOError as error:
                raise RuntimeError(f'{variant} is already being regenerated by another runner') from error
            handle.seek(0)
            handle.truncate()
            handle.write(str(os.getpid()) + '\n')
            handle.flush()
        yield


def build_model(variant, command, env):
    out = ROOT / ('output-proposed-' + variant)
    out.mkdir(parents=True, exist_ok=True)
    timing = Timings(out / 'runner-model-timings.json', variant=variant)
    log_path = out / 'regenerate-model.log'
    success = False
    print(f'MODEL_START {variant} — log: {log_path}', flush=True)
    try:
        with log_path.open('w') as log, timing.phase(variant + '.model'):
            run(command, env, log=log)
        success = True
        return {'variant': variant, 'seconds': timing.events[-1]['seconds'], 'log': str(log_path)}
    finally:
        timing.write(success=success)
        print('MODEL_' + ('DONE' if success else 'FAILED'), variant, flush=True)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--variant', choices=('compact', 'planning', 'all'), default='all',
                        help='Build only this design (default: both)')
    parser.add_argument('--jobs', type=int, choices=(1, 2), default=2,
                        help='Maximum concurrent native model builds (default: 2; use 1 to reduce memory load)')
    parser.add_argument('--appearance-only', action='store_true', help='Refresh exterior finishes from a verified completed model; refuse architecture changes')
    parser.add_argument('--force', action='store_true', help='Rebuild even when checksums match')
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument('--models-only', action='store_true', help='Skip drawing packs and the viewer build')
    mode.add_argument('--viewer-only', action='store_true', help='Build model and viewer; skip drawing packs')
    parser.add_argument('--exchange', action='store_true', help='Also export SketchUp and USDZ for selected designs and existing')
    parser.add_argument('--renders', action='store_true', help='Render matching views of selected designs and existing')
    args = parser.parse_args(argv)
    blender = next((p for p in (
        Path.home() / 'Applications/Blender.app/Contents/MacOS/Blender',
        Path('/Applications/Blender.app/Contents/MacOS/Blender'),
    ) if p.is_file()), None)
    if not blender:
        raise SystemExit('Blender not found')
    python = ROOT / '.venv/bin/python'
    variants = ('compact', 'planning') if args.variant == 'all' else (args.variant,)
    # Lock before writing a runner timing report: an overlapping invocation must
    # not overwrite the successful/in-progress invocation's report either.
    with selected_build_lock(variants):
        timings = Timings(ROOT / f'regenerate-{args.variant}-timings.json', variants=variants, jobs=args.jobs)
        succeeded = False

        def timed(label, command, env=None, cwd=None):
            with timings.phase(label):
                run(command, env, cwd)

        try:
            pending = []
            for variant in variants:
                with timings.phase(variant + '.freshness'):
                    fresh, reason = (False, 'forced') if args.force else current_build(ROOT, variant, blender)
                print(('SKIP' if fresh else 'BUILD'), variant, reason, flush=True)
                if not fresh:
                    script = 'scripts/refresh_exterior_appearance.py' if args.appearance_only else 'scripts/build_extension_proposal.py'
                    command = [blender, '--background', '--python-exit-code', '1', '--python', script]
                    if args.appearance_only:
                        command.extend(['--', variant])
                    pending.append((variant, command, os.environ | {'PROPOSAL_VARIANT': variant}))
            results = []
            if pending:
                # Per-model logs/timers are independent. The parent records wall
                # time for the group and does not sum overlapping child stages.
                with timings.phase('native_models'):
                    errors = []
                    with ThreadPoolExecutor(max_workers=args.jobs) as pool:
                        futures = {pool.submit(build_model, *job): job[0] for job in pending}
                        for future in as_completed(futures):
                            try:
                                results.append(future.result())
                            except Exception as error:
                                errors.append(error)
                                print('MODEL_ERROR', futures[future], str(error), flush=True)
                    if errors:
                        raise errors[0]
            timings.metadata['model_results'] = results
            # No consumer sees a half-completed pair: export/draw/view only once
            # every selected native model has completed successfully.
            if args.exchange:
                env = os.environ | {'ASHLEY_OUTPUT': 'output-walkthrough'}
                timed('existing.sketchup', [python, 'scripts/export_sketchup.py'], env)
                timed('existing.usdz', [blender, '--background', '--python-exit-code', '1',
                                      '--python', 'scripts/export_mac_preview.py'], env)
                for variant in variants:
                    env = os.environ | {'PROPOSAL_VARIANT': variant}
                    timed(variant + '.sketchup', [python, 'scripts/export_sketchup.py'],
                          env | {'ASHLEY_OUTPUT': 'output-proposed-' + variant})
                    timed(variant + '.usdz', [blender, '--background', '--python-exit-code', '1',
                          '--python', 'scripts/export_proposal_mac_preview.py'], env)
            if args.renders:
                for variant, original in [(variants[0], '1')] + [(v, '0') for v in variants]:
                    timed(('existing' if original == '1' else variant) + '.renders',
                          [blender, '--background', '--python-exit-code', '1', '--python', 'scripts/render_proposal.py'],
                          os.environ | {'PROPOSAL_VARIANT': variant, 'PROPOSAL_COMPARE_ORIGINAL': original,
                                        'PROPOSAL_VIEWS': 'aerial-southwest,rear-house',
                                        'PROPOSAL_SAMPLES': '12', 'PROPOSAL_WIDTH': '1000'})
            if not args.models_only and not args.viewer_only:
                for variant in variants:
                    command = [python, '-m', 'scripts.planning_drawings.build_pack', '--variant', variant]
                    timed(variant + '.drawings', command + (['--force'] if args.force else []))
                    timed(variant + '.check_drawings', command + ['--check'])
            if not args.models_only:
                timed('viewer', ['npm', 'run', 'build'], cwd=ROOT / 'walkthrough')
            succeeded = True
        finally:
            timings.write(success=succeeded)


if __name__ == '__main__':
    main()
