const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const source=p=>'/source?path='+encodeURIComponent(p);
const draftKey='ashley-whole-house-review-drafts-v1';
let comparisons={},data,state,token,selected,filtered=[],longMode=false,dirty=new Map(),saving=false,saveTimer,blocked=false,conflictState=null;
const decision=id=>state.decisions[id]??{status:'unreviewed',notes:''};
function stash(){try{dirty.size?localStorage.setItem(draftKey,JSON.stringify([...dirty])):localStorage.removeItem(draftKey);}catch{}}
function saveStatus(text){$('save-status').textContent=text;}
function stats(){const counts={approved:0,deferred:0,rejected:0,unreviewed:0};for(const x of data.items)counts[decision(x.id).status]++;const total=100-counts.unreviewed;$('progress').value=total;$('progress-text').textContent=`${total} of 100 reviewed`;$('counts').innerHTML=Object.entries(counts).map(([k,v])=>`<span><b>${v}</b> ${k}</span>`).join('');}
function select(id,focus=false){selected=data.items.find(x=>x.id===id);if(!selected)return;history.replaceState(null,'','#'+id);renderList();renderDetail();if(focus){$('detail').focus({preventScroll:true});if(innerWidth<=700)$('detail').scrollIntoView({behavior:'smooth',block:'start'});}}
function filter(selectFirst=false){const query=$('search').value.trim().toLowerCase();filtered=data.items.filter(x=>(!$('photos-only').checked||comparisons[x.id]?.status==='ready')&&(!$('area').value||x.area===$('area').value)&&(!$('status').value||decision(x.id).status===$('status').value)&&(!$('priority').value||($('priority').value==='recommended'?x.recommendedFirst:x.priority===$('priority').value))&&(!query||[x.id,x.title,x.area,x.observation,x.proposal,x.benefit,decision(x.id).notes].join(' ').toLowerCase().includes(query)));$('results').textContent=`${filtered.length} proposal${filtered.length===1?'':'s'} shown${filtered.length<100?' of 100':''}`;renderList();if(selectFirst===true&&filtered.length&&!filtered.some(x=>x.id===selected?.id))select(filtered[0].id);if(longMode)renderLong();}
function renderList(){const list=$('list');const top=list.scrollTop;list.innerHTML=filtered.length?filtered.map(x=>`<button class="proposal-row" data-id="${x.id}" aria-current="${selected?.id===x.id}"><span class="row-top"><span>${x.id}</span><span class="badge ${decision(x.id).status}">${decision(x.id).status}</span></span><strong>${esc(x.title)}</strong><span class="row-sub">${esc(x.area)} · ${x.scale} · ${x.substantial?'Larger design move':x.priority+' priority'}</span></button>`).join(''):'<p class="empty">No matching proposals. Try another room or clear the filters.</p>';list.scrollTop=top;list.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>select(b.dataset.id,true));}
function comparison(x){const c=comparisons[x.id];if(!c||c.status!=='ready')return `<section class="model-comparison pending"><h3>Before & after · from the 3D model</h3><p>This proposal’s matched model renders are not ready yet.</p></section>`;return `<section class="model-comparison"><h3>Before & after · from the 3D model</h3><div class="photo-pair">${[['before','Before · baseline 3D model'],['after',c.afterLabel]].map(([k,label])=>`<figure><figcaption>${esc(label)}</figcaption><a href="${source(c[k])}" target="_blank" rel="noopener"><img src="${source(c[k])}" alt="${esc(label)}: ${esc(x.title)}" loading="lazy"></a></figure>`).join('')}</div><p>${esc(c.caption)}</p><p class="decision-hint">${esc(c.baseline)} Open either image for full size. ${c.afterLabel.includes('built locally')?'Owner-approved change integrated locally.':'Separate proposal; not applied to the house.'}</p><a href="${source(c.manifest)}" target="_blank" rel="noopener">Render provenance</a> · <a href="${source(c.preview)}" download>Download 3D preview</a></section>`;}
function core(x){return `<p class="eyebrow">${x.id} / ${esc(x.area)}</p><h2>${esc(x.title)}</h2><div class="detail-meta"><span class="meta-pill">${x.priority} priority</span><span class="meta-pill">${x.scale} change</span><span class="meta-pill">${esc(x.basis)}</span></div>${comparison(x)}<h3>What I found</h3><p class="observation">${esc(x.observation)}</p><div class="proposal-main"><h3>Proposed improvement</h3>${esc(x.proposal)}</div><div class="two-up"><div><h3>Why it helps</h3><p>${esc(x.benefit)}</p></div><div><h3>The trade-off</h3><p>${esc(x.tradeoff)}</p></div></div><div class="check"><h3>How we would check it</h3><p>${esc(x.validation)}</p></div><p class="scope-line"><strong>Applies to:</strong> ${esc(x.scope)}</p>`;}
function renderDetail(){if(!selected)return;const x=selected,d=decision(x.id);$('detail').innerHTML=`<button class="back-list">↑ Back to proposal list</button>${core(x)}<details class="evidence"><summary>Evidence${x.plan?' & drawings':''}</summary>${x.plan?`<figure><a href="${source(x.plan)}" target="_blank" rel="noopener"><img src="${source(x.plan)}" alt="Concept drawing for ${esc(x.area)}" loading="lazy"></a><figcaption>${esc(x.planCaption??'Current brochure plan; concept geometry, not a measured survey.')} Open to inspect at full size.</figcaption></figure>`:''}<ul>${x.sources.map(p=>`<li><a href="${source(p)}" target="_blank" rel="noopener">${esc(p)}</a></li>`).join('')}</ul>${x.references?.length?`<p>Design references</p><ul>${x.references.map(r=>`<li><a href="${esc(r.url)}" target="_blank" rel="noopener">${esc(r.title)}</a></li>`).join('')}</ul>`:''}<p class="decision-hint">A design opportunity is a suggestion, not a claim that the current room is faulty. Older source notes may predate later owner decisions.</p></details>${d.outdated?`<p class="decision-hint"><strong>This proposal changed since your ${esc(d.previousStatus)} decision. Please review it again; your notes are retained.</strong></p>`:''}<div class="actions" aria-label="Your decision"><button data-status="approved" aria-pressed="${d.status==='approved'}">✓ Approve</button><button data-status="deferred" aria-pressed="${d.status==='deferred'}">Defer</button><button data-status="rejected" aria-pressed="${d.status==='rejected'}">Reject</button><button class="reset" data-status="unreviewed">Reset decision</button></div><label class="notes-label" for="notes">Your notes or conditions</label><textarea id="notes" class="notes" maxlength="10000" rows="3" placeholder="For example: approve, but keep the current furniture…">${esc(d.notes)}</textarea><p class="decision-hint">All decisions are reversible. Notes and choices save locally; no model changes are run.</p><div class="stepper"><button id="previous">← Previous</button><button id="next-unreviewed">Next unreviewed →</button></div>`;
$('detail').querySelector('.back-list').onclick=()=>$('list').scrollIntoView({behavior:'smooth'});
$('detail').querySelectorAll('[data-status]').forEach(b=>b.onclick=()=>{change(x.id,{...decision(x.id),status:b.dataset.status});$('detail').querySelectorAll('[data-status][aria-pressed]').forEach(c=>c.setAttribute('aria-pressed',String(c.dataset.status===b.dataset.status)));filter();});
$('notes').oninput=()=>change(x.id,{...decision(x.id),notes:$('notes').value});
$('previous').onclick=()=>{const pool=filtered.length?filtered:data.items;const i=pool.findIndex(v=>v.id===x.id);select(pool[(i-1+pool.length)%pool.length].id,true);};
$('next-unreviewed').onclick=()=>{const pool=filtered.length?filtered:data.items;const i=pool.findIndex(v=>v.id===x.id);const cycle=[...pool.slice(i+1),...pool.slice(0,i+1)];const next=cycle.find(v=>decision(v.id).status==='unreviewed'&&v.id!==x.id);if(next)select(next.id,true);else{saveStatus('No more unreviewed proposals in this filter.');$('status').focus();}};
}
function renderLong(){$('long-list').innerHTML=filtered.length?filtered.map(x=>`<article><button class="open-item" data-id="${x.id}">Review this proposal →</button>${core(x)}<p><strong>Decision:</strong> <span class="badge ${decision(x.id).status}">${decision(x.id).status}</span></p>${decision(x.id).notes?`<p><strong>Your notes:</strong> ${esc(decision(x.id).notes)}</p>`:''}</article>`).join(''):'<p class="empty">No proposals match these filters.</p>';$('long-list').querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{toggleLong(false);select(b.dataset.id,true);});}
function toggleLong(value){longMode=value;document.querySelector('.workspace').hidden=value;$('long-list').hidden=!value;$('all-mode').setAttribute('aria-pressed',String(value));$('all-mode').textContent=value?'Return to focused review':'Read as one long list';if(value)renderLong();}
function change(id,entry){const clean={status:entry.status,notes:entry.notes};state.decisions[id]=clean;dirty.set(id,clean);stash();stats();saveStatus('Unsaved changes…');clearTimeout(saveTimer);saveTimer=setTimeout(flush,450);}
function alertError(message,conflict=false){const box=$('alert');box.hidden=false;box.innerHTML=`<strong>${esc(message)}</strong><div><button id="retry">${conflict?'Retry my unsaved changes':'Retry saving'}</button><button id="reload-saved">Reload saved decisions</button><button id="download-draft">Download unsaved draft</button></div>`;$('retry').onclick=()=>{if(conflictState){const drafts=new Map(dirty);state=conflictState;for(const [id,d]of drafts)state.decisions[id]=d;conflictState=null;stats();filter();renderDetail();}blocked=false;box.hidden=true;flush();};$('reload-saved').onclick=async()=>{downloadDraft();dirty.clear();stash();await boot();};$('download-draft').onclick=downloadDraft;}
function downloadDraft(){download({savedRevision:state.revision,drafts:Object.fromEntries(dirty)},'ashley-review-unsaved-draft.json');}
function download(value,name){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function flush(){clearTimeout(saveTimer);if(saving||blocked)return;saving=true;
try{while(dirty.size){const[id,entry]=dirty.entries().next().value;saveStatus('Saving to local file…');let response;try{response=await fetch('/api/decision',{method:'POST',headers:{'Content-Type':'application/json','X-Review-Token':token},body:JSON.stringify({id,...entry,revision:state.revision,proposalHash:data.items.find(x=>x.id===id).proposalHash})});}catch{throw Error('The local server is unavailable. Your unsaved draft is retained in this browser.');}const result=await response.json();if(!response.ok){if(response.status===409)conflictState=result.state;throw Error(result.error??'Unable to save.');}state.revision=result.revision;if(JSON.stringify(dirty.get(id))===JSON.stringify(entry)){dirty.delete(id);state.decisions[id]=result.decision;}stash();}saveStatus('Saved to local file');$('alert').hidden=true;}
catch(error){blocked=true;saveStatus('Not saved — action needed');alertError(error.message,Boolean(conflictState));}finally{saving=false;}}
async function exportFile(fmt){await flush();while(saving)await new Promise(resolve=>setTimeout(resolve,50));if(dirty.size||blocked){alertError('Save the pending decisions before exporting, or download your unsaved draft.',Boolean(conflictState));return;}const a=document.createElement('a');a.href='/api/export?format='+fmt;a.download=fmt==='md'?'ashley-heights-review.md':'ashley-heights-review.json';a.click();}
async function boot(){try{const response=await fetch('/api/review');if(!response.ok)throw Error('Review data could not be loaded.');const payload=await response.json();comparisons=payload.comparisons??{};data=payload.data;$('photo-count').textContent=`(${Object.values(comparisons).filter(c=>c.status==='ready').length}/100 ready)`;state=payload.state;token=payload.token;blocked=false;conflictState=null;$('alert').hidden=true;$('storage-location').textContent='Saved on this Mac · '+payload.storage;$('area').innerHTML='<option value="">All areas</option>'+[...new Set(data.items.map(x=>x.area))].map(x=>`<option>${esc(x)}</option>`).join('');selected=data.items.find(x=>x.id===location.hash.slice(1))??data.items[0];if(location.hash&&selected&&!selected.recommendedFirst)$('priority').value='';stats();filter(true);renderDetail();saveStatus(state.revision?'Saved to local file':'Ready · all proposals unreviewed');let cached=[];try{cached=JSON.parse(localStorage.getItem(draftKey)??'[]');}catch{}if(cached.length){dirty=new Map(cached.filter(([id,d])=>data.items.some(x=>x.id===id)&&['approved','deferred','rejected','unreviewed'].includes(d.status)&&typeof d.notes==='string'));if(dirty.size){for(const[id,d]of dirty)state.decisions[id]=d;blocked=true;stats();filter();renderDetail();saveStatus('Recovered unsaved draft — review before saving');alertError('An unsaved draft was recovered from this browser. Retry saving to keep it, or reload the saved decisions.');}}}catch(error){saveStatus('Could not connect');$('alert').hidden=false;$('alert').textContent=error.message+' Start the local review server and refresh.';}}
['search','area','status','priority'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',()=>filter(true)));
$('photos-only').onchange=()=>filter(true);
$('clear-filters').onclick=()=>{$('photos-only').checked=false;for(const id of ['search','area','status','priority'])$(id).value='';filter();};
$('all-mode').onclick=()=>toggleLong(!longMode);$('export-md').onclick=()=>exportFile('md');$('export-json').onclick=()=>exportFile('json');
window.addEventListener('beforeunload',e=>{if(dirty.size){e.preventDefault();e.returnValue='';}});
window.addEventListener('hashchange',()=>select(location.hash.slice(1)));
await boot();
