"""Curated owner proposals; does not modify the model or owner decisions."""
import json, hashlib
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
OUT=Path(__file__).resolve().parent
items=[]
def group(area,source,rows,category='Interior',scope='Both proposed designs'):
 for line in rows.strip().split('\n'):
  title,priority,scale,basis,observation,change,benefit,tradeoff,check=line.split('|')
  items.append(dict(id=f'AH-{len(items)+1:03}',area=area,category=category,title=title,priority=priority,scale=scale,basis=basis,observation=observation,proposal=change,benefit=benefit,tradeoff=tradeoff,validation=check,sources=[source],scope=scope))

group('Entrance & hall','proposal/interiors/leisure/arrival.json','''
Give shallow coat storage a usable internal system|Medium|Small|Design opportunity|The revised cabinet already wraps the corner and is only 320 mm deep, with coats hanging end-on.|Develop pull-forward coat rails, a separate wet-coat bay and removable drip trays inside the existing outline.|Coats become easy to retrieve without making the entrance cabinet deeper.|Rails need room to extend while someone stands in front; wet clothes need ventilation.|Show a full winter coat, an extended rail and two people arriving without blocking the door.
Make the shoe bench work for boots and bags|Medium|Small|Design opportunity|The existing bench sits under gym glazing and has a clear seated approach.|Divide its storage into everyday shoes, one taller boot bay and a temporary bag landing; keep the top largely clear.|Supports actual arrival routines without another piece of hall furniture.|A boot bay reduces the total number of shoe slots.|Check typical shoe/boot sizes and the occupied bench against the adjoining route.
Add a discreet arrival charging drawer|Low|Small|Design opportunity|The shallow key return is already integrated into the entrance corner.|Fit one ventilated drawer with charging and a removable key tray, with its cable route drawn back to an accessible supply.|Keeps keys and charging clutter off the entrance surface.|Heat, charger clearance and drawer travel need checking; avoid locking essential controls inside.|Demonstrate drawer opening and charging access without crossing the coat rail movement.
Give the double-height entrance separate lighting scenes|High|Medium|Design opportunity|The gallery is double-height and connects directly to the original hall.|Develop arrival, evening and cleaning scenes using concealed ambient light, restrained wall light and useful task light at storage.|Makes a tall space welcoming at night while keeping the oak/ivory architecture calm.|More circuits and control coordination; no extra pendant should compete with the existing composition.|Compare fixed-camera evening views and confirm accessible switches at both ends.
Keep rainwater and grit at the entrance threshold|Medium|Medium|Design opportunity|The entrance is the main transition from a four-car forecourt into the house.|Detail a flush replaceable mat well and a sheltered set-down position within the existing arrival footprint.|Reduces tracked dirt and makes wet-weather arrival more comfortable.|Threshold depth, drainage and door clearances must be coordinated before specifying a mat.|Draw threshold section, open door and mat replacement access.
Compose one clear view from the front door|Medium|Small|Design opportunity|The entrance links several angled spaces; earlier brochure views obscured this relationship.|Choose one restrained artwork or lit plaster surface as the arrival focus and align the normal eye-level camera with the real route.|Gives arrival a legible destination without adding more furniture.|The focus must not hide glazing, structure or the coat cupboard.|Review the actual door-open view and reverse view in the native model, without wide-angle distortion.
''')
group('Kitchen & garden dining','proposal/interiors/kitchen/quiet-oak.json','''
Test the kitchen with two cooks and the dishwasher open|High|Medium|Design opportunity|The accepted Quiet oak kitchen has a compact 1.05 x 1.60 m island and several adjoining social routes.|Create an occupied-use plan and refine only handles, door hinging or local fittings if the fridge/dishwasher/cooking routines conflict.|Protects the chosen appearance while making everyday use more convincing.|Any required cabinet adjustment must preserve the selected island and accepted room arrangement where possible.|Run cooking, unloading and garden-passage scenarios with actual appliance door envelopes.
Give breakfast appliances a closing cupboard|Medium|Medium|Design opportunity|The selected kitchen has a detailed oven tower and clean oak work surfaces.|Develop a ventilated breakfast cupboard with pull-out work surface for toaster/coffee kit, fitted into an existing tall run if space permits.|Keeps the calm kitchen look during ordinary use.|Consumes food-storage volume and needs appliance-specific heat clearance.|Inventory appliances and demonstrate operation with cupboard doors fully open; reject if it steals the main preparation surface.
Make waste sorting part of the preparation route|Medium|Small|Design opportunity|The kitchen study establishes preparation, cooking and dining but the selected brief does not record a household waste capacity target.|Allocate labelled removable recycling, food-waste and general-waste bins within the existing base units near preparation.|Reduces trips and avoids loose bins beside the island.|Bin capacity competes with pan storage.|Show a chopping-to-bin routine and full-bin removal without blocking appliance doors.
Refine island socket and cable placement|Medium|Small|Design opportunity|The island is an accepted social and preparation centre, not just a visual feature.|Locate discreet accessible power on an end face away from seated knees and wet preparation, with cable routes contained inside joinery.|Makes occasional appliances and laptops usable without trailing leads across a route.|Socket location must be coordinated with drawers, overhang and electrical design.|Demonstrate a mixer and laptop in use with all cables clear of standing and seated circulation.
Light the working edge without glare|Medium|Small|Design opportunity|The kitchen palette relies on pale stone and oak, which should remain the visual focus.|Refine concealed task lighting to illuminate worktops from in front of users, with separate dining dimming and no exposed LED dots.|Improves preparation visibility while retaining a soft evening atmosphere.|Diffusers and drivers need accessible replacement space.|Review cooking-eye and seated-eye views at day and night, including reflections in stone and glazing.
Add a garden-table serving home|Medium|Medium|Design opportunity|The everyday garden table is 2.40 x 1.00 m and sits beyond the kitchen.|Develop a shallow serving and crockery unit on an existing free wall, sized only after checking occupied chairs and garden doors.|Keeps plates and serving dishes nearby without filling the table with clutter.|Additional joinery is worthwhile only if it leaves the route generous.|Show six occupied places, a serving person and the garden door open before choosing the unit size.
Give garden dining controllable afternoon light|High|Medium|Design opportunity|Garden dining is deliberately placed in the bright rear extension.|Study discreet external shading or recessed blinds that preserve the glazing and roof form, then choose the least intrusive option.|Reduces glare and makes the room comfortable across more of the day.|External shading can affect the elevation; solar performance needs assessment rather than a visual guess.|Compare seasonal sun positions, table-eye glare and the closed-blind appearance before committing.
''')
group('Formal lounge & dining','proposal/interiors/leisure/formal.json','''
Make the ten-person table setting a real hosting plan|High|Small|Recorded constraint|The table seats six daily and extends from 1.80 to 2.80 m for eight to ten.|Draw the fully occupied extended arrangement, including serving and both hall doors, and define which occasional chair positions genuinely work.|Makes the promised hosting capacity clear without enlarging the everyday table.|Ten places may be less comfortable than eight; do not hide that trade-off.|Measure chair pullback and the serving route with ten full-size chairs and occupied seats.
Store the extension leaf and spare chairs deliberately|Medium|Medium|Design opportunity|The formal table is extendable; the source specification does not assign a storage location for its leaf or extra chairs.|Reserve accessible protected leaf storage and a home for occasional chairs in existing nearby joinery or the garage store.|Avoids a beautiful table that is inconvenient to extend.|Leaf storage can consume a long cupboard; stacking chairs must still fit the room style.|Record real folded/stacked sizes and demonstrate one-person retrieval.
Refine the drinks cabinet as a serving station|Medium|Small|Design opportunity|A 430 mm-deep drinks cabinet already exists at the dining end.|Fit a removable spill tray, glass dividers and a discreet preparation light inside the existing cabinet, retaining the warm neutral finish.|Turns the approved drinks area into a practical hosting detail.|Useful worktop space must take priority over display bottles and ornaments.|Show a host preparing two drinks while guests pass and the cooler door opens.
Give each formal sofa a proper reading position|Low|Small|Design opportunity|Two facing sofas make a conversation group; the central table alone is not equally reachable from every seat.|Add or reposition compact end tables and shaded reading lights at the outer sofa ends, with concealed power.|Supports books and drinks without changing the accepted sofa style or colour.|Too many objects would clutter the room; use only where reach is poor.|Check seated reach, shade glare and door routes from all four sofa ends.
''')
group('Office','proposal/interiors/leisure/office.json','''
Hide desk cables with a serviceable route|Medium|Small|Design opportunity|The office desk faces into the room rather than sitting against a wall.|Develop an underside cable tray and a discreet floor or perimeter feed that does not cross the chair path.|Keeps the open desk arrangement tidy and safe to use.|Floor feeds can require construction work; a perimeter solution may be less invisible.|Trace power/data to the wall and show the chair rotating and pulling back.
Control video-call light at the bay|Medium|Small|Design opportunity|The retained bay is the office daylight source and the desk is deliberately side-lit.|Coordinate a translucent daytime blind with a monitor/camera position that keeps the face evenly lit and avoids screen reflections.|Makes the office work for calls without blacking out the room.|A blind changes the filtered view; keep the existing window composition.|Compare seated webcam framing and monitor glare in morning and afternoon conditions.
Fit office storage to real equipment|Low|Small|Design opportunity|The office includes closed storage but the brief does not list printer, files or network equipment.|Lay out one equipment bay with ventilation, paper access and a charging shelf inside the current storage footprint.|Prevents printers and cables migrating onto the desk.|A equipment bay sacrifices some book/file capacity.|Use actual equipment dimensions and show paper replenishment and service access.
''')
group('Principal bedroom','proposal/interiors/principal/bedroom.json','''
Give both bed occupants complete night controls|High|Small|Design opportunity|The accepted bed is against the south wall with two 600 mm bedsides and a fixed TV.|Coordinate reading light, low night light, main-light off and charging at both bedsides without changing the headboard.|Makes the room feel luxurious through daily convenience rather than a new visual theme.|Control plates can look busy; keep a simple repeatable layout.|Show controls reachable from both pillows with a phone, book and water on each bedside.
Create a quiet route from bed to bathroom|High|Medium|Design opportunity|The bathroom is reached through the shifted dressing room from the main bedroom.|Add shielded low-level lighting on that route, with a gentle night scene and manual override.|Supports one person getting up without flooding the bed with light.|Sensors must not trigger unnecessarily from movement in bed.|Review the route from both sleeping positions at night and verify no direct glare.
Make the two equal TVs behave independently|Medium|Small|Design opportunity|Both principal screens are now the same size, with separate bed and sofa viewing positions.|Specify independent control and audio zones, including headphones for one viewer, while retaining both fixed screens.|Avoids operating the wrong screen and reduces conflict between study, sleep and TV.|Two open-room TVs cannot provide acoustic separation; simultaneous loud viewing remains unsuitable.|Demonstrate one screen on, one off and individual audio control from bed, sofa and desk.
Refine the rounded L desk for working comfort|Medium|Small|Design opportunity|The approved desk has equal 1.80 m arms, 700 mm depth and rounded inner/outer corners.|Resolve knee space, cable access and a monitor position along one arm while preserving the swivel view to the sofa TV.|Keeps the sculptural desk useful for actual work.|Storage below either arm can restrict chair rotation; avoid filling the corner with drawers.|Check a seated user at both arms, chair rotation and the TV sightline with a monitor present.
Give the low gable alcove a deliberate seated purpose|High|Medium|Recorded constraint|The roof-preserving central opening is 1.20 m wide and 1.70 m high, so many adults must duck.|Develop the space beyond as an occasional seated window nook with no essential through-route or everyday standing storage.|Makes the accepted low opening read as an intentional retreat rather than a misleading full-height doorway.|Access still requires ducking; this does not solve the structural support design.|Draw a section with a standing adult at the opening and a seated adult beyond, keeping roof and garage unchanged.
Refine bedroom blackout at the retained windows|Medium|Small|Design opportunity|The suite has several east windows and a vaulted west alcove; the accepted layout depends on their outlook.|Detail discreet blackout layers and side returns without changing window positions or headboard form.|Improves sleep and TV viewing while preserving daytime light.|Blind housings must fit the actual recesses and avoid the moved partition junctions.|Show blinds fully raised/lowered at all openings and check service access.
Soften the sofa zone without changing its identity|Low|Small|Design opportunity|The separate sofa group is established and its TV size is owner-selected.|Refine the rug size, one textured throw and a reachable side table in warm neutral tones, keeping the current sofa and fixed TV.|Differentiates relaxing from sleeping through texture and use, not a colour overhaul.|Extra soft furnishings must not creep into the suite entry or dressing route.|Review the entrance and desk views, then check the occupied sofa route.
''')
group('Principal bathroom & wardrobe','proposal/interiors/principal/ensuite.json','''
Make the sculptural bath detail buildable and cleanable|High|Medium|Recorded constraint|The accepted larger bath sits in a 1.90 x 0.90 m footprint close to two walls; floor loading and final product clearances remain unresolved.|Develop a bath-side section with a real product, accessible waste connection and a deliberate cleanable edge or service zone.|Preserves the lavish appearance while avoiding an impossible-to-clean gap.|The final bath may need a small position adjustment within the approved room.|Check manufacturer installation access, cleaning reach and support with the project engineer/plumber.
Protect privacy at the bath window without losing sky|High|Medium|Recorded constraint|The new bath window is 1.80 m wide with a sill about 1.10 m above the bathroom floor.|Compare a lower privacy treatment with a discreet adjustable blind, using actual neighbour sightlines before choosing.|Keeps daylight and the bath focal point without unintended overlooking.|Permanent obscuration reduces the outlook; a blind needs user operation.|Draw sightlines from relevant exterior positions to a seated bath user and standing shower user.
Add an easy-to-reach dry towel position|Medium|Small|Design opportunity|The plan defines bath, shower and vanity use zones but towel reach is not captured by those polygons.|Locate a warm towel rail or concealed towel shelf reachable from the shower and bath without crossing the wet floor.|Adds practical spa comfort without more decorative clutter.|Heat output, surface temperature and electrical/plumbing zones require coordination.|Show wet-to-dry movements and accessible controls with both fixtures in use.
Light faces at the vanity, not just the stone|Medium|Small|Design opportunity|The long floating vanity is part of the accepted bathroom composition.|Develop softly diffused vertical or mirror-integrated light with a separate low evening scene.|Improves grooming and gives the bathroom a more considered hotel-like finish.|Visible fixtures could compete with the mirror; choose the least intrusive arrangement.|Review face-level shadows and mirror glare from both basin positions.
Organise the walk-through wardrobe by actual clothing|High|Medium|Design opportunity|The dressing room has two hanging runs and drawers beneath the window, within the accepted shifted partitions.|Allocate double hanging, long hanging, shoes and folded items using a household clothing inventory rather than room area alone.|Makes the existing wardrobe work harder without making the room bigger again.|Increasing one storage type reduces another; the inventory determines the balance.|Provide a measured internal elevation and check drawer operation with someone passing to the bathroom.
Add a useful dressing mirror with frontal light|Medium|Small|Design opportunity|The walk-through room must preserve both bedroom-to-bath circulation and window access.|Integrate a full-length mirror on an existing suitable door/panel with soft frontal light, avoiding a freestanding mirror.|Creates a complete dressing routine without occupying the central floor.|The mirror location must avoid unwanted bathroom views and glare.|Show a full-body view at a usable standing distance with doors in normal positions.
Separate laundry from clean dressing storage|Medium|Small|Design opportunity|The bathroom and wardrobe form one daily route and already contain substantial fitted storage.|Reserve ventilated removable laundry bins near the bathroom end, divided only as the household actually sorts washing.|Stops laundry accumulating beside the bed or within clean-clothes shelves.|Bins reduce drawer capacity and need a carrying route to the utility.|Check bin removal, carrying clearance and that the bathroom door can still open fully.
''')
group('Other bedrooms','proposal/interiors/leisure/sidebed.json','''
Ease the side-bedroom foot pinch without losing bed access|High|Medium|Recorded constraint|The revised side bedroom has good 940/835 mm side aisles but only 665 mm beside the ensuite at the bed foot.|Compare a genuinely shorter bed frame or a carefully rounded foot detail before considering any further partition movement.|Improves the tightest everyday route while preserving the successful bed position and both bedsides.|The mattress size and proper frame dimensions must remain real; a drawing-only slim bed is not acceptable.|Measure the complete selected frame and walk the foot route with bedding overhang included.
Give Bedroom 2 wardrobe ends a deliberate finish|Low|Small|Design opportunity|Bedroom 2 places a long wardrobe close to the entrance composition; the native study makes that joinery a prominent first view.|Refine the exposed end with a shallow recess, softened edge or flush panel joint in the same oak, rather than a new colour.|Makes the entry feel designed without changing the accepted bed or storage capacity.|Any recess reduces internal volume and must not obstruct the door.|Compare ordinary doorway views and check the open door against the finished panel.
Protect Bedroom 3 balcony access during dressing|Medium|Small|Recorded constraint|Bedroom 3 retains balcony access and its documented foot/wardrobe routes are single-file.|Coordinate wardrobe hardware and the window treatment so an open cupboard or blind does not trap the balcony approach.|Makes the compact room easier to use without moving walls.|Sliding fronts may change usable opening width; retain storage access.|Check dressing, bed-making and balcony-door-open states separately and together where realistic.
Use wall-mounted bedside details in Bedroom 4|Medium|Small|Recorded constraint|Bedroom 4 retains a full double and compact single-file routes, with shallow bedsides preserving the entrance turn.|Refine wall-fixed reading lights and charging ledges within the current bedside envelopes, keeping the existing headboard.|Frees useful bedside surface and avoids wider furniture in a tight room.|Wall services need coordination and must remain accessible.|Check reachable controls from both pillows and the complete door sweep.
Give guest luggage a proper temporary home|Medium|Small|Design opportunity|The garden guest suite has substantial sliding storage, a reading chair and a fixed 43-inch TV.|Reserve a lower wardrobe bay or folding luggage perch sized for an open suitcase rather than adding a permanent bench in the route.|Guests can unpack without using the bed or blocking balcony access.|Luggage space reduces clothing storage; a folding perch needs a stored position.|Show an open suitcase, occupied bed and ensuite door all in their normal use states.
Vary bedroom textiles while preserving approved headboards|Low|Small|Owner preference|The owner rejected a blue headboard redesign but wants subtle variety within the same house style.|Prepare a restrained room-by-room textile schedule using ivory, oatmeal, warm grey and muted natural accents only on replaceable layers.|Gives bedrooms individual character without changing their furniture identity.|Too many finishes would fragment the house; cap each room at one quiet accent.|Present side-by-side existing and proposed textile swatches with headboards and joinery locked.
''')
group('Shared bathrooms & cloakroom','proposal/interiors/leisure/guestbath.json','''
Resolve the guest shower handle and opening together|High|Small|Recorded constraint|The guest shower concept limits its inward leaf to 85 degrees to keep a double-sided handle clear of the lining.|Select a compatible hinge/handle set or alternative door system that provides reliable entry inside the existing shower footprint.|Avoids relying on an arbitrary model stop that the real product cannot reproduce.|Changing the enclosure system can alter access and cleaning; do not shrink the shower casually.|Use manufacturer drawings to test full travel, handle clearance, entry and emergency access.
Give shared bathrooms concealed daily-item storage|Medium|Small|Design opportunity|The family bathroom and cloakroom have floating vanities, but compact counters can quickly collect toiletries.|Develop shallow mirror storage where construction permits and drawer dividers within existing vanities, retaining the warm neutral design.|Keeps the counters calm while making everyday items reachable.|A recessed cabinet needs a suitable wall; a surface unit must not project awkwardly.|Check wall build-up, tap/mirror relationship and open cabinet access with a user at the basin.
Coordinate bathroom lighting with nighttime use|Medium|Small|Design opportunity|Several bedrooms share landing access to the family bathroom, and the cloakroom opens into the main living circulation.|Add low-output night scenes and easy manual controls, with the main grooming light separately switched.|Makes nighttime use less disruptive without another decorative redesign.|Sensors and timers can frustrate users if there is no clear override.|Walk bed-to-bath and hall-to-cloakroom routes under the proposed night scene.
''')
group('Landings & loft','proposal/interiors/leisure/hobby.json','''
Make the low loft bridge constraint visible in the design|High|Medium|Recorded constraint|The retained bridge is recorded at roughly 1.78–1.90 m headroom, below comfortable standing height for some users.|Produce a finished-floor section and develop a clearly legible low-headroom transition; assess a local non-roof structural refinement only if feasible.|Prevents a seemingly normal corridor concealing a known comfort constraint.|Signs or lighting do not fix headroom; any physical improvement needs structure and stair review.|Review a full-height human section along the complete route and label unresolved dimensions explicitly.
Give the under-stair reading corner comfortable task light|Medium|Small|Design opportunity|The chair has already moved under the upper stair, with recorded seated/approach headroom.|Refine a shielded reading light and reachable book/drink surface within the accepted placement.|Makes the nook genuinely usable without moving it back into the landing.|A projecting fitting could reduce headroom or glare into the stair.|Review a seated reader and a person standing up, including the light fitting envelope.
Keep linen storage useful without filling the landing|Medium|Small|Design opportunity|The landing already has sliding-front linen storage designed to avoid door swings into the route.|Assign shelf spacing to bedding sets and add removable labelled baskets for spare pillows and towels.|Uses existing joinery better and reduces bedroom clutter.|Oversized baskets can be awkward to carry on stairs.|Check shelf reach and one-person removal of a full bedding set without blocking bedroom doors.
Give the hobby room a resettable working layout|Medium|Medium|Design opportunity|The original-house loft has a mobile project table, two working places and an intentionally open centre.|Design two tested states: projects in progress and cleared family lounge, with locking castors and a defined table parking position.|Makes the multifunctional brief practical without specialist equipment or permanent clutter.|Switching modes takes effort; avoid a layout that needs every chair moved for normal access.|Show both states with storage open and the bridge/stair route clear.
Use task lighting where the loft ceiling is low|Medium|Small|Recorded constraint|The dormer structural headroom is about 2.09 m before finishes, so suspended fittings can be intrusive.|Refine shallow ceiling lighting and local table/reading lights with protected cable routes.|Improves usable light while preserving scarce headroom.|Surface fittings still consume depth and may glare under low ceilings.|Draw a section through lights, standing users and the project table; review normal seated views.
Make the loft-bedroom narrow bedside purposeful|Medium|Small|Recorded constraint|The doorway-side bedside is only 205 mm wide to preserve the ensuite approach; the opposite side is 410 mm.|Design a compact wall-integrated phone/glasses pocket and reading control within that 205 mm zone, leaving the larger bedside unchanged.|Provides essentials on both sides without reintroducing removed eaves cabinets.|It will not function like a full bedside table; keep expectations honest.|Check reach from the pillow and the bedroom/ensuite door paths with bedding in place.
''')
group('Gym','proposal/interiors/leisure/gym.json','''
Separate running mode from rowing mode clearly|High|Medium|Recorded constraint|The current gym specification uses shared activity space; rowing is checked with the bike unoccupied.|Develop two explicit equipment states with simple storage positions and a clear setup sequence, preserving the gate-facing treadmills.|Prevents the room looking as though all machines can be used simultaneously when they cannot.|A mode-based gym is less convenient for several users; the trade-off should be owner-selected.|Draw full manufacturer operating zones in each state and verify the utility and courtyard routes remain usable.
Keep treadmill cables out of the circulation strip|High|Small|Design opportunity|Both treadmills face the front gates and the gym doorway has already moved south.|Coordinate power points and protected cable routes at the front ends, avoiding the rear safety zones and doorway.|Retains the approved orientation while improving practical installation.|Electrical provision depends on selected machines and floor/wall construction.|Show the actual plug/lead path for each machine and confirm no extension lead crosses a route.
Design vibration control below gym equipment|High|Medium|Design opportunity|The gym sits in the front wing below principal accommodation and includes two treadmills and free weights.|Develop an equipment-specific resilient floor build-up and isolated weight-drop area within the existing room.|Reduces disturbance and improves the feel of the gym without changing decor.|Additional floor thickness affects thresholds; acoustic benefit needs specialist assessment.|Review equipment loads, threshold section and impact/vibration strategy before final flooring selection.
Give exercise sessions fresh air without cold draughts|High|Medium|Recorded constraint|The gym room brief leaves ventilation unresolved despite multiple exercise machines.|Coordinate quiet supply/extract or purge ventilation with actual occupancy, avoiding air aimed directly at runners' faces.|Makes the room more comfortable during hard exercise.|Duct routes, plant noise and external grilles affect other design decisions.|Assess occupancy and heat gains, then show grille locations and maintenance access in the model.
''')
group('Cinema','proposal/interiors/leisure/cinema.json','''
Increase cinema passing comfort with a slimmer centre table|High|Medium|Recorded constraint|The cinema has a 650 mm front approach and seated viewers must tuck their knees in for someone to pass.|Compare a shallower fixed table or small reachable side surfaces while keeping four seats in one row.|Improves entry during a film without returning to a raised second row.|Less central table area; do not introduce loose pieces into the side aisle.|Show occupied seats, realistic leg positions and a person reaching every seat.
Make acoustic treatment part of the accepted dark design|High|Medium|Recorded constraint|The dark fabric lining is modelled but does not establish sound isolation or acoustic performance.|Develop an acoustic lining and door-seal concept concealed within the current cinema palette.|Improves dialogue clarity and limits disturbance without changing the approved mood.|Real treatment consumes room width/depth; rerun seating and aisle checks afterward.|Prepare wall/ceiling sections and an acoustic design review, distinguishing absorption from isolation.
Coordinate projector, speakers and service access|High|Medium|Recorded constraint|The screen and seating sightlines are established, but final projector/speaker specifications remain unresolved.|Select a coherent equipment layout with lens throw, speaker positions, ventilation and removable access panels.|Avoids detailed visual equipment that cannot be installed or maintained.|Actual products may need small mounting changes; preserve screen/seat relationship where possible.|Check manufacturer envelopes, image geometry and access for replacing each device.
Add a film-entry lighting scene|Medium|Small|Design opportunity|The cinema is entered along the side of a single seating row.|Develop low shielded aisle guidance with a brief entrance scene and independent full cleaning light.|Makes late entry easier without washing out the screen.|Light spill and automatic triggering need tuning.|Review the doorway open during a dark scene from all four seats.
''')
group('Wine bar & games','proposal/interiors/leisure/bar.json','''
Test a wider route around the pool cue zone|High|Medium|Recorded constraint|The recorded full cue zone leaves about 622 mm beside the stair guard on the route to the sofa.|Compare small pool-table translations or rotations using the full 1.525 m cue allowance before changing any fixed bar joinery.|Could improve circulation while retaining a real six-foot table and the games brief.|Moving the table can harm darts or cinema access; a larger aisle may not be achievable in this shell.|Overlay all cue positions, occupied stools, darts zone and the stair-to-sofa route for each candidate.
Improve the bar through texture, not a green colour scheme|Medium|Small|Owner preference|The owner rejected the green bar treatment and wants the bar to relate more closely to the pool area.|Refine the bar with warm oak relief, pale stone and restrained bronze details, using the accepted pool palette as the reference.|Adds depth and character while keeping the house visually coherent.|Too much fluting or metallic surface can look busy; retain a calm stone counter.|Present a material-only comparison with layout and neutral upholstery locked.
Give darts a deliberate storage and wall-protection detail|Medium|Small|Design opportunity|The games area already has a correctly positioned board and a separate throwing zone.|Integrate a restrained protective surround, scorekeeping surface and closed dart storage within the existing wall plane.|Makes the activity complete without a themed pub aesthetic.|A thicker surround must not reduce the throwing distance or conflict with passage.|Measure from the finished board face and show a player plus a passing guest outside the throwing zone.
Separate coolers and glasses from decorative display|Medium|Small|Design opportunity|The fitted bar has a 1.302 m serving aisle, coolers, shelves and three stools.|Develop cooler ventilation and removable glass storage with a clear tray landing, reducing display objects where necessary.|Makes the bar easier to serve from and maintain while retaining its improved appearance.|Less display may look quieter; ventilation grilles need careful integration.|Show two drinks being prepared, a cooler open and another person passing behind the host.
''')
group('Utility','proposal/interiors/leisure/utility.json','''
Add a drying solution that folds completely away|Medium|Medium|Design opportunity|The utility has side-by-side machines and a continuous worktop but no recorded everyday air-drying allocation.|Study a retractable rail or ventilated drying cupboard inside the existing room without spanning the main aisle.|Supports delicates and reduces loose drying racks elsewhere in the house.|A drying cupboard costs storage and needs ventilation; overhead rails may affect reach.|Show garments hanging and both doors/appliances operating before selecting the solution.
Reserve a dirty-arrival drop zone from the garage|Medium|Small|Design opportunity|The utility connects garage and gym, and the east run is already organised for washing and folding.|Allocate a removable tray and small robust landing for muddy shoes, sports kit and shopping at the garage end.|Keeps dirty items off clean laundry and kitchen surfaces.|Must not consume the useful folding surface or narrow the door approach.|Walk garage-to-utility with shopping and wet gym kit while an appliance is open.
Make laundry sorting and carrying easier|Low|Small|Design opportunity|The fitted run already includes two pull-out hamper bins and tall linen storage.|Refine bin heights, handles and a temporary basket perch so wet and clean loads can move through in sequence.|Improves use of the current layout without adding cabinets.|A basket perch can become clutter; it should fold away or be part of the counter.|Demonstrate washer unloading, folding and carrying a full basket through both doorways.
''')
group('Garage & parking','proposal/interiors/leisure/garage.json','''
Fit the garage to the actual household cars|High|Medium|Recorded constraint|Current checks use two 4.40 x 1.80 m cars and 42-degree front-door openings; the arrangement is staggered.|Replace concept car envelopes with the household vehicles including mirrors, door travel and boot opening before fixing storage.|Protects the double-garage promise and avoids unusable fitted cupboards.|Larger cars may require less garage joinery or different staggering.|Test driver/passenger exit and carrying shopping to the utility with both real cars parked.
Give bikes a retrievable storage position|Medium|Medium|Recorded constraint|The planning actions explicitly leave a workable bin/cycle layout unresolved.|Study wall or floor bike storage in a perimeter zone with a realistic retrieval path past parked cars.|Makes cycling storage useful rather than a token plan symbol.|Hanging bikes may be difficult for heavier cycles; storage competes with the workbench.|Show the heaviest intended bike being removed while both cars are parked.
Plan EV charging without trailing leads to the entrance|High|Medium|Design opportunity|The brief requires two garage spaces and four exterior parking spaces, creating several possible charging positions.|Develop discreet charger locations and cable reach to the likely daily vehicles, with capacity assessment before product choice.|Supports everyday charging while keeping pedestrian arrival clear.|Electrical supply and load management may govern the solution; not every bay needs a charger.|Draw plugged-in vehicles and cables with the gate, boot and entrance routes in use.
''')
group('Pool & garden','proposal/interiors/leisure/poolgarden.json','''
Integrate the pool cover before refining the deck|High|Large|Recorded constraint|The 8.00 x 3.50 m pool is fixed in the brief, but cover and pool safety systems remain unresolved.|Develop a cover system with its housing, guides and service access fitted into the current pool/deck design.|Avoids a late bulky cover reel undermining the accepted pool area.|Different cover systems affect deck space, cost and construction; no safety performance is assumed.|Show fully open/closed states, maintenance access and compatibility with coping and loungers.
Make the pool-to-changing route comfortable when wet|High|Medium|Recorded constraint|The summer house floor is raised above the pool terrace, and the existing route includes steps.|Detail a clearly lit wet route with consistent slip-resistant finishes and a well-resolved step/handhold arrangement; assess a gentle alternative only if it fits.|Improves the actual swimming routine while retaining the garden buildings.|A ramp could consume substantial garden space; do not claim level access without measured slopes.|Draw levels and sections from pool edge to changing bench and WC, including nighttime use.
Keep towel storage useful in damp weather|Medium|Small|Design opportunity|The pavilion already includes a towel/cushion storage unit.|Divide dry towels, used towels and outdoor cushions into ventilated, removable compartments within the same footprint.|Keeps the pool area orderly and reduces damp textiles being carried indoors.|Ventilation and weather protection must work together; storage is not a drying room.|Check door opening, rain exposure and one-person removal of each compartment.
Add a discreet rinse point near changing|Medium|Medium|Design opportunity|The pool and garden WC/changing area are separate connected spaces, with final services still unresolved.|Study a screened warm-water rinse point close to existing service routes, using the same stone/oak vocabulary.|Reduces water and dirt carried through the house and completes the pool routine.|Needs drainage, frost protection and privacy; omit if it cannot fit without crowding.|Show screening sightlines, shower standing space and the dry pedestrian route.
Improve shade without reversing the loungers again|Medium|Medium|Owner preference|The three loungers are already rotated as requested, with about 950 mm clear strip beside them.|Compare discreet removable shade positions that serve the loungers while retaining their approved orientation and the pool route.|Makes the accepted lounging arrangement comfortable in strong sun.|Umbrella bases or posts can become obstacles; wind restraint matters.|Test shade at useful times and show base/canopy envelopes clear of circulation and pool edge.
Keep pool equipment serviceable and acoustically discreet|High|Large|Recorded constraint|Pool/spa services are not resolved in the room study.|Reserve a properly ventilated equipment location with replacement access, pipe routes and noise separation from seating and neighbours.|Prevents plant from becoming an afterthought that spoils the garden.|A service enclosure consumes space and may need planning/design review.|Show the largest equipment replacement path, drainage and an acoustic assessment before choosing enclosure details.
Give the garden a restrained evening lighting plan|Medium|Medium|Design opportunity|The scheme has pool, pavilion, workshop and several level changes rather than one simple lawn.|Develop a low-glare hierarchy for paths, steps and one or two planted focal points, with quiet late-night settings.|Makes the whole garden usable and coherent without floodlighting it.|Exterior light can disturb bedrooms, neighbours and wildlife; keep output and hours purposeful.|Review views from seating, bedrooms and boundaries, with fittings aimed and shielded.
Refine the planting as year-round structure|Medium|Medium|Design opportunity|The model establishes mature trees and garden zones, but the owner-facing studies emphasise furniture more than seasonal planting.|Prepare a restrained planting concept with evergreen structure, softer seasonal layers and maintenance access around pool and paths.|Adds depth and individuality while supporting the accepted pool palette.|Plant size, roots, leaf fall and maintenance must suit the actual site; no tree removal is assumed.|Show mature spread, winter appearance and clear paths, then coordinate with the arboricultural survey.
''',category='Garden',scope='Proposed only; existing-garden refinements separately assessed for Planning')
group('Roof terrace','proposal/interiors/leisure/terrace.json','''
Resolve terrace drains and thresholds as one detail|High|Large|Recorded constraint|The terrace has three flush rooflights, retained guards and an unresolved waterproofing/roof build-up.|Develop a coordinated section through door threshold, paving falls, rooflights, outlets and overflow routes.|Preserves the desired outdoor room without hiding essential drainage beneath furniture.|Finished levels may affect thresholds and guard heights; construction details need specialist design.|Check ponding/overflow paths, access to every outlet and finished-level dimensions.
Give terrace cushions and furniture a weather plan|Medium|Small|Recorded constraint|The design says loose cushions are stored indoors in bad weather; a cushion box already occupies part of the terrace.|Size storage to the actual cushion set and define secure furniture positions for wind without adding heavy planters casually.|Makes the terrace easier to use and close down.|Added weight and fixings affect structure/waterproofing; a box may not hold the whole set.|Demonstrate all cushions stored and furniture restrained with rooflights and routes clear.
Balance terrace privacy with the seated outlook|High|Medium|Design opportunity|The terrace has a retained west privacy screen and two seating groups.|Check seated and standing neighbour sightlines, then refine only the necessary screen portions using the existing material family.|Avoids over-screening the terrace while protecting privacy where it matters.|Taller screens alter wind loading and the external appearance.|Compare views from each seat and relevant neighbour windows against surveyed levels.
''',category='Garden',scope='Proposed only')
group('Workshop','proposal/interiors/leisure/workshop.json','''
Fit workshop storage to a chosen activity set|Medium|Medium|Recorded constraint|The workshop is a general craft concept with a 1.60 x 0.80 m mobile table; final tools and extraction are unresolved.|Develop a modular storage/tool layout for the owner's likely activities, keeping the main bench and mobile centre table.|Makes the room useful without pretending one generic workshop supports every hobby.|Some activities are incompatible; specialist dusty/noisy work may need a separate setup.|Show the largest workpiece, tool operation and storage/retrieval route in the retained shell.
Make the workshop approach usable for carrying things|Medium|Medium|Owner preference|The stepping stones have already been removed; the retained approach is a narrow garden strip route.|Refine a continuous firm surface, threshold and subtle lighting suitable for carrying a project or wheeled trolley.|Improves access without reintroducing the rejected stones.|Widening may affect planting and drainage; preserve the plot and tree constraints.|Check actual path width, slope and doorway approach with the intended trolley or largest carried item.
''',category='Garden',scope='Proposed only')
group('Exterior & site','proposal/START-HERE.md','''
Make brick setbacks read clearly in construction details|High|Medium|Recorded constraint|The side-wing setback is 900 mm in the current specification, and front entrance/garage projections have repeatedly been flattened in images.|Develop coordinated corner, reveal and movement-joint details that preserve those real offsets in the model and drawing set.|Makes the brick composition legible and reduces ambiguous wall junctions.|Joint positions must follow construction design, not just visual preference.|Compare plan, elevation and oblique native views with explicit offset dimensions.
Resolve the garage-gable support with a real load path|High|Large|Recorded constraint|The accepted principal cross-wall and floor-concealed beam remain a structural concept, not engineered steelwork.|Ask the structural design to establish the floor-level beam, bearings and wall/opening support while retaining the garage roof form.|Addresses the owner's original support concern rather than merely improving the visible joint.|Beam depth or bearings may affect floors/partitions; any consequential design change needs separate review.|Provide a section and load-path sketch tied to survey and structural calculations before claiming buildability.
Detail flat dormer caps and tiled cheeks consistently|High|Medium|Owner preference|The owner requires tiled dormer fronts/cheeks but flat caps; generated images have repeatedly changed that roof shape.|Create one explicit dormer detail with cap edge, flashing, rainwater route and tile termination used by both designs and all visuals.|Preserves the intended architecture and makes the roof junction credible.|Real waterproofing edges may alter small visible dimensions.|Check roof section and native close-up views before accepting any enhanced exterior image.
Coordinate rainwater goods with the brick elevations|Medium|Medium|Design opportunity|The house combines original roofs, connector and front wing, creating several junctions and levels.|Review gutter/outlet/downpipe positions as a complete route and align them discreetly with existing corners where feasible.|Avoids arbitrary pipes interrupting glazing or ending above awkward roof junctions.|Drainage capacity and outlet placement can overrule visual symmetry.|Trace every roof area to an outlet and lawful drainage strategy; show maintenance access.
Protect a clear pedestrian arrival through the forecourt|High|Medium|Recorded constraint|The full brief retains four outside spaces alongside the double garage and gate.|Refine paving, lighting and parking positions to maintain an obvious route from gate and parked cars to the entrance.|Makes arrival safer and more welcoming without reducing the parking brief by stealth.|The fourth compact bay may constrain passage; actual vehicles and tracking decide feasibility.|Test all six cars parked, gate open and one person carrying shopping to the front door.
Design bins as a serviced part of the frontage|Medium|Medium|Recorded constraint|The planning register says bin/cycle provision remains a concept requiring a workable layout.|Locate screened bin storage with ventilation, full lid opening and a practical collection-day route, using materials sympathetic to the brick frontage.|Avoids bins becoming the dominant entrance feature or blocking parking.|Storage can compete with gate visibility and planting; collection requirements need confirmation.|Show bins in storage and being wheeled to collection with vehicles parked.
''',category='Exterior')
group('Whole-house comfort','proposal/interiors/DESIGN-PRINCIPLES.md','''
Coordinate heating and ventilation with the furnished rooms|High|Large|Recorded constraint|Room studies repeatedly leave services unresolved, while furniture and glazing positions are now detailed.|Develop a whole-house service concept with plant space, ducts/pipe routes, accessible filters and room controls before more decorative detail.|Reduces late conflicts with wardrobes, ceilings and quiet rooms.|Services may require local boxing or reduced storage; assess options before choosing.|Overlay routes with current furniture, structure and ceiling sections and identify every maintenance access point.
Give noisy rooms and bedrooms an acoustic adjacency plan|High|Large|Design opportunity|The brief puts cinema/bar in the basement, gym in the front wing and sleeping rooms above/near leisure uses.|Map noise sources and quiet rooms, then develop targeted floor, partition and door strategies rather than treating every wall identically.|Protects sleep and study while retaining the full leisure brief.|Effective isolation may consume space or require construction changes.|Review paths through floors, stairs, doors and services, not just surface finishes.
Plan summer comfort from the actual glazing and use|High|Large|Design opportunity|Large garden glazing, a double-height entrance, loft rooms and multiple TVs create different comfort conditions.|Assess orientation, shading, secure ventilation and internal heat gains, prioritising passive measures before any cooling proposal.|Makes the home comfortable without adding visible equipment blindly.|A thermal assessment needs verified fabric/glazing and weather assumptions; applicability of regulations is separate.|Compare overheating risk by room and show how selected measures affect the approved elevations.
Keep future adaptability within the existing brief|Medium|Medium|Design opportunity|Most bedrooms have ensuites, while some routes and low-headroom areas are deliberately compact.|Identify a practical guest/sleeping and washing arrangement for temporary reduced mobility and reserve useful future service provisions.|Improves resilience without redesigning the whole house around an unrequested accessibility standard.|This may require a specific local doorway or fixture change; it is not a claim of full accessibility.|Test the chosen everyday route and bathroom use with realistic assistance/space needs, then offer any building change separately.
''',category='Whole house')
group('Brochure & drawings','scripts/brochure/build_house_brochure_spatial.py','''
Add a concise decision index to the long brochure|Medium|Small|Observed|The current brochure has 95 pages, 61 images and 27 area plans.|Add a clickable room index with page references and a short list of unresolved decisions, while keeping the full visual sequence.|Makes the expanded brochure useful for review rather than only browsing.|Another navigation layer must not duplicate several competing contents pages.|Verify every link/page reference after pagination and test PDF navigation on desktop and tablet.
Show occupied-use plans beside the tightest rooms|High|Medium|Recorded constraint|Several room plans look comfortable when furniture is unoccupied, while source reviews record single-file or shared-use constraints.|Add a small alternate diagram for cinema, games, gym, garage and compact bedrooms showing occupied chairs, doors and activity envelopes.|Makes the brochure honest about how spaces work without cluttering every architectural plan.|Diagrams need a clear legend and should not imply measured survey certainty.|Cross-check each envelope against current specifications and label concept dimensions.
Use native geometry as the locked base for exterior photos|High|Medium|Owner preference|Dormer caps and facade offsets have repeatedly drifted in enhanced exterior pictures.|Adopt a geometry-locked native render workflow for architecture, limiting enhancement to finishes, light and planting that preserve silhouettes/openings.|Improves credibility and reduces repeated corrections of beautiful but inaccurate images.|Native photorealism takes more lighting/material work and may be slower per image.|Compare masks, edges, roof forms and openings against the native reference before publication.
Bring plans, sections and elevations onto one revision|High|Medium|Observed|The principal gable change was patched into public models while native exports had a rebuild limitation; planning packs are separately generated.|Create one drawing issue with shared source hashes, room names, scale bars and sections through roof/level changes.|Makes the set more professional and exposes which documents reflect the latest design.|Full regeneration may require resolving the native build first; old issues should remain archived.|Check source hashes and key dimensions across all drawings and state survey/concept status.
Show each exterior viewpoint on the site plan accurately|Medium|Small|Observed|The brochure includes a neighbourhood viewpoint guide, and source footprint generation recently needed correction.|Generate camera markers, direction arrows and image labels from the actual camera records and surveyed context when available.|Helps readers understand where they are looking without invented camera placement.|Neighbour/context geometry is still indicative until verified.|Compare each marker/heading with the rendered camera and label uncertain surrounding context.
''',category='Presentation',scope='Local brochure and drawing workflow')
group('Model & build workflow','scripts/publication/stage_github_pages.py','''
Make native and web model parity a release requirement|High|Medium|Observed|The gable wall was added to web GLBs while Blender startup problems delayed native export reconciliation.|Add a release report that compares design feature hashes and critical geometry across native, web, plans and brochure inputs.|Prevents one format silently lagging behind another after a targeted patch.|Requires reliable native export or an explicit blocked/stale status; do not mark parity from filenames alone.|Deliberately stale one fixture export in a test and ensure the release report catches it.
Build only the changed room and dependent outputs|High|Large|Design opportunity|The pipeline has room studies, source fingerprints and recent delivery caches; whole-design work is still costly for small changes.|Audit current dependency tracking and extend it so one room change invalidates only affected geometry, navigation, plans and images.|Makes iterative design faster while preserving correctness.|An incomplete dependency graph risks stale output; existing working caches should be reused.|Compare a full clean build with incremental builds for room, roof and shared-material changes.
Add interior/exterior finish regression views|High|Medium|Owner preference|Repeated owner corrections concerned exterior brick/white faces and interior reveals switching incorrectly.|Maintain fixed reference cameras and face classifications for both designs and all finish modes, including known troublesome walls.|Catches recurring finish mistakes before the owner sees them.|Image checks need tolerance for lighting; material/face assertions should support them.|Exercise brick/render switches and verify internal faces, dormer cheeks and flat caps separately.
Load detailed room geometry when it is needed|Medium|Large|Design opportunity|The models include tiny appliance and furniture details, while the deployed package remains large despite compression improvements.|Measure initial loading cost, then prototype room-based loading or distance detail levels that preserve close-up detail on demand.|Could make first entry and mobile browsing faster without deleting the details the owner requested.|Streaming boundaries can cause pop-in and navigation complexity; measure before committing.|Compare cold-load time, memory, room-entry delay and visual parity on a representative phone and desktop.
Keep project status and approvals in one current register|High|Small|Observed|Several source JSON/Markdown files still say working, unapproved or unpublished after later integration and deployment.|Create a current issue register linking owner approvals, source revisions, verification and published release, with old notes marked historical.|Reduces confusion and prevents repeating completed work or treating outdated images as current.|Maintaining the register must be part of the normal build/review process, not another manual duplicate.|Trace a room from approved brief through source, model, brochure and live release without contradictory current status.
''',category='Technical',scope='Local authoring and release workflow')

from refine_proposals import refine
refine(items,ROOT)
from substantial_proposals import apply as apply_substantial
apply_substantial(items)

assert len(items)==100,len(items)
assert len({x['title'] for x in items})==100
for item in items:
 assert (ROOT/item['sources'][0]).is_file(),item['sources']
for item in items:
 item.pop('proposalHash',None)
 item['proposalHash']=hashlib.sha256(json.dumps(item,sort_keys=True,ensure_ascii=False).encode()).hexdigest()
result={'version':2,'title':'Ashley Heights — 100 considered improvements','created':'2026-09-29','baseline':'Proposed with brick exterior; existing owner-approved interiors retained','status':'Proposals only — none implemented or published by this review','approvalMeaning':'Approval records your preferred direction. It does not run model changes, commit code or publish. Any material design consequences will be brought back for review.','items':items}
(OUT/'proposals.json').write_text(json.dumps(result,indent=2,ensure_ascii=False)+'\n')
print('Created',len(items),'proposals')
