"""Evidence-led revisions to the initial 100-item draft."""
from pathlib import Path

def refine(items,root):
 by={x['id']:x for x in items}
 def update(n,**values):by[f'AH-{n:03}'].update(values)
 update(3,title='Give parcel deliveries a discreet temporary home',basis='Design opportunity',observation='The entrance already has a key tray, USB-C charging and a bag bay. Parcel deliveries are a different storage need.',proposal='Reserve a removable parcel tray or clearly sized lower bay near arrival, keeping packages out of the stair and front-door routes.',benefit='Stops deliveries accumulating in the entrance without duplicating the existing charging station.',tradeoff='A useful parcel bay consumes some everyday storage; avoid a large permanent cabinet for rare oversized boxes.',validation='Show a typical delivery box and two people arriving, with the front door, coat fronts and stair route clear.',sources=['proposal/interiors/leisure/arrival.json','scripts/interiors/proposal_arrival_interiors.py'])
 update(18,title='Complete the office desk power feed',observation='The office already has an underside cable tray, grommet and monitor lead. The modelled cable stops at the desk; a room-to-desk supply route is not established by those details.',proposal='Resolve the final wall/floor-to-desk power and data route, retaining the existing tray and grommet and keeping the chair path clear.',sources=['proposal/interiors/leisure/office.json','scripts/interiors/proposal_office_interiors.py'])
 update(30,title='Put a dry towel within reach of the shower exit',observation='A towel warmer already sits on the east side of the principal bathroom. The shower is on the opposite side, so the practical reach deserves a separate check.',proposal='Add a compact towel hook or shelf at the shower exit if the measured reach to the existing warmer is awkward; keep the bath-side warmer and all fixture positions.',tradeoff='The new detail must not intrude into the shower approach or be soaked during use.',validation='Show a user stepping out of the shower and reaching a dry towel without crossing the central wet floor.',sources=['proposal/interiors/principal/ensuite.json','scripts/studies/preview_principal_ensuite.py'])
 update(31,title='Reconcile the detailed design with a measured survey',area='Survey & planning',category='Planning',priority='High',scale='Large',basis='Recorded constraint',observation='The planning action register explicitly says the reconstruction, boundaries, levels and floorspace are provisional; detailed furnishings now depend on them.',proposal='Create one survey-reconciliation issue identifying differences between measured building/topographic data and the model, with proposed local corrections ranked by impact on the accepted design.',benefit='Concentrates changes where real dimensions require them and protects the minimal-alteration brief.',tradeoff='A survey may reveal unavoidable changes; approval here is for the reconciliation approach, not spending or appointing consultants.',validation='Produce a dimension-difference schedule and marked plans before altering accepted rooms.',scope='Both designs and site context',sources=['proposal/planning/REQUIRED-ACTIONS.md','proposal/START-HERE.md'])
 update(33,title='Add a compact sit-down dressing perch',observation='The wardrobe already includes a full-length mirror. The current specification does not allocate a seat for putting on shoes.',proposal='Test a pull-out or fold-away upholstered perch integrated into existing joinery, preserving the central bathroom route and current mirror.',benefit='Completes the dressing routine without enlarging the wardrobe or adding a loose chair.',tradeoff='The perch consumes storage and must be stable when loaded; it cannot occupy the through-route while left open.',validation='Show a seated user, drawers open and another person passing to the bathroom; reject the perch if those uses cannot coexist.',sources=['proposal/interiors/principal/ensuite.json','scripts/studies/preview_principal_ensuite.py'])
 update(38,title='Use lift-up storage in the compact fourth bedroom',observation='Bedroom 4 already has wall-mounted reading lights, USB-C charging and shallow floating bedsides. Its compact routes limit extra storage furniture.',proposal='Explore a lift-up storage base within the accepted full bed-frame envelope, keeping the mattress size and headboard unchanged.',benefit='Adds bedding storage without projecting drawers into the narrow bedside aisles.',tradeoff='A lift mechanism needs a suitable mattress weight, reliable support and clearance to bedding/headboard; it is less convenient than an open shelf.',validation='Use a real mechanism envelope and demonstrate one-person access without moving bedside furniture.',sources=['proposal/interiors/leisure/bedroom4.json','scripts/interiors/proposal_bedroom4_interiors.py'])
 update(43,title='Make the minimum-change planning case measurable',area='Survey & planning',category='Planning',priority='High',scale='Medium',basis='Recorded constraint',observation='The brief favours minimal alterations and the planning register flags front-wing scale and unverified baseline areas.',proposal='Prepare a retained/removed/new fabric and volume comparison for Existing, Proposed and Planning, then identify which small envelope reductions would most reduce bulk if the planning review requires them.',benefit='Supports an informed planning conversation while protecting the rooms and features that matter most.',tradeoff='No arbitrary percentage proves acceptability; this is an evidence study, not permission or approval to shrink rooms.',validation='Tie quantities to a verified original-house baseline, draw the street massing and list the actual room consequences of each fallback.',scope='Both designs; separate application baseline',sources=['proposal/planning/REQUIRED-ACTIONS.md','proposal/specs/design-spec-compact.json','proposal/specs/design-spec-planning.json'])
 update(45,title='Check neighbour daylight before choosing further exterior refinements',area='Survey & planning',category='Planning',priority='High',scale='Medium',basis='Recorded constraint',observation='Neighbour heights and flank-window relationships are still indicative in the planning evidence, while the wing and dormers materially shape the adjoining outlook.',proposal='Build a verified neighbour-window and level model, then assess daylight, sunlight and outlook around the changed elevations before selecting any mitigation.',benefit='Directs any small roof/window/setback adjustment toward an actual concern rather than guesswork.',tradeoff='A specialist study may be needed; a simple diagram or 45-degree screen is not a guarantee of consent.',validation='Identify affected windows and outdoor spaces, state survey uncertainty and compare any mitigation against the unchanged scheme.',scope='Both designs and relevant neighbouring context',sources=['proposal/planning/REQUIRED-ACTIONS.md','proposal/specs/planning-context.json'])
 update(95,title='Add source-image comparisons to exterior review pages',observation='The site viewpoint markers already come from the camera manifest. The repeated problem has been visual differences between enhanced pictures and their native references.',proposal='Add a native/enhanced comparison control for exterior studies, with matched framing and a short record of approved appearance-only changes.',benefit='Lets the owner spot altered roofs, missing setbacks or invented openings immediately.',tradeoff='Two image sets add download weight; load the reference only when requested.',validation='Verify camera/framing correspondence and inspect dormer caps, facade offsets and openings at full resolution.',sources=['scripts/brochure/brochure_site_plans.py','scripts/brochure/build_house_brochure_spatial.py'])

 update(20,title='Soften kitchen-to-TV sound without enclosing the lounge',area='TV lounge',observation='The accepted TV lounge is open to the kitchen/garden living sequence, so cookware, conversation and television share the same air volume.',proposal='Develop a discreet acoustic ceiling or wall treatment within the ivory/oak finishes and tune the lounge rug/curtains, retaining the open plan and fixed screen.',benefit='Reduces reverberation and improves listening comfort without adding doors to the accepted open living space.',tradeoff='Soft finishes improve absorption, not sound isolation; the kitchen will still be audible.',validation='Assess speech/TV use with cooking underway and check any treatment against glazing, ceiling height and the selected room appearance.',sources=['proposal/interiors/kitchen/quiet-oak.json','scripts/interiors/proposal_kitchen_interiors.py'])
 update(27,title='Give the upstairs family lounge a shared device home',area='Upstairs family lounge',observation='The family lounge already has a compact homework desk, games storage and a reading sofa; chargers and tablets need a shared storage routine.',proposal='Reserve one ventilated charging drawer in the existing east storage run, with removable device dividers and a clear tray for current homework.',benefit='Keeps the small desk and games table available without adding furniture or changing the neutral palette.',tradeoff='Devices create heat and consume storage; the drawer needs appropriate charging hardware and ventilation.',validation='Show the actual family devices stored, cables managed and the drawer open without blocking the terrace or bedroom approach.',sources=['proposal/interiors/leisure/family.json','scripts/interiors/proposal_family_interiors.py'])
 update(36,title='Make the loft shower work at finished head height',area='Loft bedroom & ensuite',priority='High',scale='Medium',basis='Recorded constraint',observation='The loft suite records approximately 2.09 m dormer headroom above structural floor, before floor and ceiling finishes reduce it.',proposal='Draw a finished section through the shower and choose a compact head/arm arrangement and tray build-up that preserves useful head clearance, retaining the dormer roof.',benefit='Makes the loft ensuite credible for standing use rather than judging it from a floor plan alone.',tradeoff='Tall users may still find the room constrained; a low-profile fitting cannot solve an unsuitable roof height.',validation='Show finished floor, tray, shower head and a range of user heights in section using actual products.',sources=['proposal/interiors/leisure/loftsuite.json','scripts/interiors/proposal_loftsuite_interiors.py'])
 update(54,basis='Measured concept comparison',observation='The current coffee table is 660 mm deep and leaves a 650 mm empty gap to the sofa. A 360 mm-deep candidate, with its screen-side edge held fixed, increases that gap to 950 mm.',proposal='Trial the shallower 360 mm table or remove the central table in favour of reachable console/side surfaces, keeping all four seats and the fixed screen.',tradeoff='Moving the table edge away improves passage but worsens seated reach. The empty gap is not the same as clear space around occupied knees.',validation='Compare both layouts with realistic occupied legs, late entry and drinks reachable from each seat.',sources=['proposal/interiors/leisure/cinema.json','revisions/whole-house-review-2026-09-29/spatial-comparisons.json'])
 update(58,title='Choose the games-room circulation compromise explicitly',basis='Measured concept comparison',observation='The full cue reservation leaves a 622.5 mm band beside the stair. The sampled layout study gains at most 75 mm by translation, with only 5 mm tolerance at the north wall; rotation does not produce a generous route.',proposal='Keep the six-foot table and develop a clearly illustrated hosting mode using a shorter cue for constrained stair-side shots, if you value wider simultaneous passage. Retain the full-cue arrangement if that playing compromise is unacceptable.',benefit='Offers a real route improvement without pretending furniture can simply be shuffled into a much larger room.',tradeoff='This changes the playing experience. A 1.40 m stair-side cue allowance plus a 75 mm table shift tests at about 800 mm body width in the simplified plan, but the north tolerance is too tight to treat as an installation solution.',validation='Choose actual cues, include finished wall/skirting tolerances and test occupied pool, darts, stools and the stair route before choosing the final position.',sources=['proposal/interiors/leisure/bar.json','revisions/whole-house-review-2026-09-29/spatial-comparisons.json'])
 update(60,title='Add discreet dart storage and scorekeeping',observation='The model already has a protective surround, board lighting and throw line. A practical scoring and secure dart-storage position is not established in the room brief.',proposal='Add a flush scorekeeping panel and small closed dart/accessory drawer outside the throwing line, retaining the existing board surround and lighting.',validation='Show a player scoring and storing darts without crossing another game or obstructing the normal cinema route.',sources=['proposal/interiors/leisure/bar.json','scripts/interiors/proposal_bar_interiors.py'])
 update(70,area='Summer house & changing',observation='The pool pavilion already has ventilated towel/cushion joinery, while the narrow summer house contains a single-user changing corner.',proposal='Coordinate the two stores as a dry-towel pickup and ventilated used-towel drop, with a modest hook/shelf at the changing bench and no extra floor cabinet.',benefit='Creates a complete changing routine and keeps damp towels separate from fresh linen.',tradeoff='The summer house is only about 1.76 m wide; even shallow fittings must stay clear of seated changing and the door.',validation='Show one person changing with clothes, a dry towel and shoes, while the WC and pool routes remain accessible.',sources=['proposal/interiors/leisure/gardenhouse.json','proposal/interiors/leisure/poolgarden.json'])
 # Exact room sources, rather than a shared group source used in the first draft.
 for n,slug in [(37,'bedroom3'),(39,'guest'),(42,'familybath'),(46,'landings'),(49,'loftsuite')]:
  by[f'AH-{n:03}']['sources']=[f'proposal/interiors/leisure/{slug}.json',f'scripts/interiors/proposal_{slug}_interiors.py']
 update(66,sources=['proposal/interiors/leisure/garage.json','proposal/planning/REQUIRED-ACTIONS.md'])
 update(86,sources=['proposal/interiors/leisure/garage.json','proposal/planning/REQUIRED-ACTIONS.md'])
 update(96,sources=['revisions/principal-gable-wall-2026-09-28/STATUS.md','scripts/interiors/principal_gable_wall.py'])
 update(97,sources=['revisions/build-speed-2026-09-25/STATUS.md'] if (root/'revisions/build-speed-2026-09-25/STATUS.md').exists() else ['scripts/build/build_extension_proposal.py'])
 update(98,sources=['scripts/interiors/proposal_interior_details.py','revisions/interiors-overnight-2026-09-27/internal-reveals-compact.json'])
 update(99,sources=['scripts/publication/model_delivery.py','walkthrough/src/model-delivery.js'])
 update(100,sources=['revisions/interiors-overnight-2026-09-27/STATUS.md','revisions/principal-gable-wall-2026-09-28/STATUS.md','proposal/START-HERE.md'])
 # Study plans are evidence of the current layout, not drawings of these proposals.
 plans={'Entrance & hall':'arrival','Kitchen & garden dining':'kitchen','Formal lounge & dining':'formal','Office':'office','Principal bedroom':'principal','Principal bathroom & wardrobe':'dressing-bath','Other bedrooms':'sidebed','Shared bathrooms & cloakroom':'guestbath','Landings & loft':'hobby','Gym':'gym','Cinema':'cinema','Wine bar & games':'bar','Utility':'utility','Garage & parking':'garage','Pool & garden':'poolgarden','Roof terrace':'terrace','Workshop':'workshop','TV lounge':'tv-lounge','Upstairs family lounge':'family','Loft bedroom & ensuite':'loftsuite','Summer house & changing':'gardenhouse'}
 specific={36:'loftsuite',37:'bedroom3',38:'bedroom4',39:'guest',40:'bedroom2',42:'familybath',46:'landings',49:'loftsuite'}
 for x in items:
  n=int(x['id'][3:]);slug=specific.get(n,plans.get(x['area']))
  if slug:
   plan=f'revisions/brochure-spatial-2026-09-28/plans/{slug}.svg'
   if (root/plan).exists():x['plan']=plan;x['planCaption']='Existing brochure concept plan — shows the baseline, not this proposed improvement. Dimensions await survey.'
  for s in x['sources']:assert (root/s).is_file(),s
 refs={
  'desk':{'title':'HSE: workstation space, glare and screen position','url':'https://www.hse.gov.uk/pubns/indg36.pdf'},
  'planning':{'title':'Sevenoaks: Residential Extensions SPD (design and amenity guidance)','url':'https://www.sevenoaks.gov.uk/downloads/download/141/residential_extensions_spd'},
  'comfort':{'title':'Government: Approved Document O overview (check project applicability separately)','url':'https://www.gov.uk/government/publications/overheating-approved-document-o'},
 }
 for n in (18,19,24):by[f'AH-{n:03}']['references']=[refs['desk']]
 for n in (29,31,43,45,78,81,83,85,86):by[f'AH-{n:03}']['references']=[refs['planning']]
 by['AH-089']['references']=[refs['comfort']]
 for x in items:
  if 'An equipment' not in x['tradeoff']:x['tradeoff']=x['tradeoff'].replace('A equipment','An equipment')

 # Measured comparisons are proposal evidence, distinct from baseline plans.
 for n,slug in [(54,'cinema'),(58,'games')]:
  x=by[f'AH-{n:03}']
  if x.get('plan'):x['sources'].append(x['plan'])
  x['plan']=f'revisions/whole-house-review-2026-09-29/{slug}-comparison.svg'
  x['planCaption']='Read-only concept comparison for this proposal. Nothing in the house model has been changed.'

 by['AH-096']['observation']='A fresh read-only parse finds six principal-gable-wall parts in both public GLBs and none in their corresponding native geometry snapshots. Web and native-export-dependent outputs disagree on this feature.'
 by['AH-096']['sources'].append('revisions/whole-house-review-2026-09-29/model-parity-audit.json')
 for n in [7,25,28,31,43,44,54,65,68,76,82,96]:by[f'AH-{n:03}']['recommendedFirst']=True
