"""Owner-directed larger design alternatives, kept separate from accepted design."""
import hashlib,json
from pathlib import Path
HERE=Path(__file__).resolve().parent
# ID | title | observation | proposal | benefit | trade-off | validation
TEXT='''
3|Replan arrival as a proper entrance sequence|The entrance combines a double-height gallery, shallow coat storage, gym glazing and a route to the original hall.|Develop a coordinated arrival layout: preserve the shallow corner coat unit, place seated shoe-changing outside the through-route, and create one clear view from the front door into the original hall. Test a discreet internal glazed screen only where it improves zoning without narrowing the route.|The entrance becomes a usable, composed room rather than a collection of furniture along a passage.|A screen may interrupt the double-height openness; omit it if the route and sightline work better without it.|Render arrival with doors open, coats in use and two people passing; compare the route to the current model.
8|Turn the kitchen tall run into a pantry and appliance wall|The kitchen has a compact island and multiple social routes; more freestanding appliances or island enlargement would compete with circulation.|Reconfigure the existing tall cabinetry into an integrated pantry, breakfast station and appliance bank. Keep the chosen island and main plumbing positions; use the tall run to take everyday clutter and preparation away from its social edge.|A more capable kitchen with a coherent storage wall and a clearer island for cooking and conversation.|Pantry capacity competes with appliance and general storage; final cabinet allocation depends on actual equipment.|Model doors and pull-outs open, check appliance ventilation and two-person use, and compare retained cabinet capacity.
12|Create an integrated garden-dining bay|The garden dining space is generous in appearance but its occupied chair and garden-door routes need to work together.|Compare a tailored banquette along a suitable solid wall with the current freestanding dining arrangement, integrating serving storage at one end and retaining a large everyday table. Keep garden glazing and door openings clear.|A more architectural dining area with a defined place in the open-plan room and potentially clearer circulation.|A banquette is less flexible and inner seats are harder to reach; do not proceed if no suitable uninterrupted wall exists.|Test the current table size with people seated, chair pullback, serving and open garden doors before choosing the bay.
14|Centre an eight-seat round table in the hexagonal dining bay|The current rectangular extending table sits east of the centre of the formal dining bay. The owner requested a round table with eight regular places centred in that area.|Compare a 1.70 m round oak pedestal table at the dining bay centre, with eight of the current upholstered chairs equally spaced around it. Re-centre the pendant and keep the lounge, windows, hall doors and drinks cabinet.|A clearer focal point that follows the room shape and gives all eight diners equal access to conversation.|Eight permanent chairs occupy more of the room every day. The west/northwest chairs are close to the drinks cabinet; access behind occupied chairs and cabinet opening must be reviewed. This option replaces the previous six-seat extending brief for comparison only.|Inspect matched native model photos and a dimensioned chair/pullback plan. Confirm door swings, cabinet access and circulation with chairs occupied and pulled out.
20|Make the TV lounge acoustically separable|The open relationship between kitchen and TV lounge makes cooking and television compete for the same sound space.|Compare a wide, pocketing glazed acoustic screen at the lounge transition, with coordinated ceiling absorption and concealed tracks. Keep it fully open for everyday family use and closed for films or calls.|A separate quiet room when useful while retaining the visual connection and accepted palette.|Pocket walls, track depth and acoustic seals need space; ordinary decorative sliding glass will not provide the same isolation.|Model the screen open and closed, check the parked leaves, thresholds and fixed TV sightlines; assess the actual assembly acoustically.
25|Make the garage-gable alcove an intentional window retreat|The accepted low central opening creates a distinct space beyond the principal bedroom, not a normal standing doorway.|Design a complete low seated retreat beyond the opening: fitted upholstered window seating, low integrated storage and concealed reading light shaped to the unchanged roof. Keep everyday wardrobe and bathroom circulation outside it.|Makes the constrained volume feel deliberate and luxurious rather than leftover space.|It remains an optional duck-through destination; the low opening is not made full-height or represented as accessible.|Render the approach and seated view using the real roof and opening; verify sitting headroom and window operation.
28|Replan the ensuite as a coherent spa room|The larger ensuite and sculptural bath are accepted, but the fixtures need a coherent spatial composition as well as more lavish materials.|Compare a unified bathing and shower zone, a calmer double-vanity wall and a discreet WC sightline screen within the enlarged bathroom. Retain the bath window and wardrobe relationship; use a flush floor wherever feasible.|The bathroom reads as a complete luxurious room with a dry dressing edge and a deliberate bath focal point.|Moving drainage, screens or the shower can add construction work; a raised bath plinth is not assumed.|Produce alternative occupied plans, wet/dry routes and matched 3D views; then check waste falls, cleaning access and floor support.
32|Design the wardrobe as complete fitted dressing architecture|The walk-through room has an important bathroom route; adding isolated furniture will make it feel busier without improving storage much.|Redesign the internal joinery as coordinated full-height runs with dedicated long hanging, double hanging, folded storage and a concealed dressing perch. Keep the accepted room size, mirror and through-route, with no central island.|More useful clothing capacity and a calmer tailored dressing room within the existing footprint.|Storage allocation must fit actual clothing; full-height joinery can feel heavy unless openings, lighting and proportions are resolved.|Compare measured hanging lengths and drawer capacities with the baseline, showing all fronts open and the route occupied.
35|Replan the side bedroom and family-room boundary together|The side bedroom still has a 665 mm foot turn despite usable side aisles. A shorter frame alone can recover at most a small amount.|Study a further local transfer of space from the family approach into the bedroom, together with a revised ensuite entrance and storage position. Compare an approximately 450 mm northward partition study with the current layout, rather than just shrinking furniture.|Potentially creates a genuinely comfortable double bedroom with a clearer arrival and ensuite route.|The family room loses area and its approach changes. The 450 mm shift is a test dimension, not a verified recommendation; keep its main seating and external openings usable.|Model both rooms together, measure occupied bed/wardrobe/door routes and reject any option that trades one pinch for another.
38|Give the compact fourth bedroom a complete guest-room layout|The fourth bedroom must accommodate a real bed, clothing and luggage without permanent clutter in the route.|Develop one coordinated bed-and-storage arrangement with full-height joinery on a suitable solid wall, an integrated occasional work/dressing surface and luggage space. Keep the accepted mattress and headboard; compare complete furniture layouts rather than extra shelves.|A small bedroom can work as a finished room instead of a bed surrounded by leftover pieces.|The room may not support every function simultaneously; the work surface may need to close away.|Show sleeping, dressing and luggage-open states with all doors and windows operating in the actual shell.
47|Make the loft a two-zone hobby and family room|The large loft has several potential uses and low roof areas; a generic furniture spread does not establish how those uses coexist.|Develop a permanent project/work zone with concealed ongoing-project storage and a separate soft family lounge, linked by a clear high-headroom route. Test sliding internal screens only where they park entirely out of the circulation.|The loft becomes a destination with two convincing uses and a practical way to leave projects unfinished.|Screens and storage can make the loft feel smaller; low eaves are not counted as normal standing space and removed eaves units are not reinstated.|Render working and cleared states; map finished headroom, stair arrival and window access before approving the layout.
50|Replan the gym and utility as a coordinated pair|Running, rowing and strength currently rely on shared activity space. Rearranging small accessories will not create simultaneous-use capacity.|Compare the current rooms with a compact stacked-laundry service wall that may release part of the gym/utility boundary for a better equipment zone. Retain both gate-facing treadmills and their rear safety areas; test any partition move only after fitting the full laundry brief.|Could improve actual exercise use and remove the need for repeated equipment setup without enlarging the external envelope.|The utility loses area and equipment/service costs may increase. Do not claim all activities can run together unless the occupied layout proves it.|Use selected equipment dimensions, door swings, laundry loading and service clearances in a combined two-room model.
58|Swap the games and lounge zones to open the basement route|The earlier pool-table search held the west sofa/TV group fixed, so the only full-cue improvement was a marginal table movement.|Move the six-foot pool table into the west bay and move the sofa to the north wall of the east bay. Remove the separate west TV/console group and use the adjacent cinema for screen viewing; keep the bar and darts area. Test the whole zone swap with full cue envelopes.|A substantial reorganisation of the leisure room, with a more direct stair-to-bar route and distinct games and conversation areas.|It gives up the separate games-room TV nook. Cueing, occupied seating and access must all be checked; furniture fit alone is insufficient.|Render the entire north room before/after, overlay the 1.525 m cue reservation and verify the circulation route around the stair and lounge.
62|Rebuild the utility around stacked laundry and a drying cupboard|The current 3.2 m service run places washer and dryer side by side with hampers, sink and tall storage.|Compare a stacked laundry tower with a ventilated full-height drying cupboard and a continuous sorting/folding surface in the space released. Keep the existing sink service wall, east window and both door openings where possible.|A utility with dedicated washing, drying and clean-folding functions rather than a row of appliances.|Stacking reduces access to the upper machine for some users; stacking hardware, ventilation and maintenance access must match real products.|Model appliance doors, basket handling and drying contents; compare storage and clear aisle widths with the current run.
66|Replan garage storage around a protected pedestrian strip|Two staggered concept cars, storage, bicycles and the utility connection all compete for the garage floor.|Develop a complete garage layout with a clearly reserved pedestrian route to the utility, one consolidated perimeter storage wall and a genuinely retrievable bike zone. Keep two car spaces and the existing garage exterior/roof.|The garage becomes usable every day, with storage and walking routes designed around parked cars.|Some current cabinetry may have to move or shrink; larger real vehicles may rule out the desired bike arrangement.|Use household vehicle envelopes, mirrors, boot and door travel, then show one person carrying shopping and one retrieving a bike.
68|Design the pool terrace as one complete outdoor room|The pool, narrow edge routes, loungers and raised changing building work as separate elements; their transitions determine daily use.|Develop one coordinated pool-side layout with integrated cover housing, a clear wet route, usable lounging positions and a distinct dry seating edge. Preserve the pool, approved lounger orientation and external house form.|A coherent leisure space with better transitions and a deliberate relationship to changing and garden seating.|Cover mechanisms and accessible service space consume deck area; additional level changes must not be hidden by attractive paving.|Render the pool covered/open and the walking route occupied, using the actual site levels and all deck clearances.
70|Turn the summer-house support rooms into a proper pool-changing suite|The pool requires a convincing place to change, shower and handle wet towels, not only more storage furniture.|Study a dedicated shower/changing arrangement within the existing garden-building envelope, retaining the outside WC and relocating some tool storage to the workshop if necessary. Connect it to the existing changing bench and pool route.|Makes the pool function as a complete daily leisure facility without assuming a new garden building.|New drainage and ventilation are required; tool storage is displaced and the existing envelope may limit the shower size.|Draw the full garden-building plan, privacy sequence, drying space and drainage route; retain useful workshop storage and realistic wet clearances.
72|Add a restrained covered poolside lounge|The pool has sun loungers, but comfortable shade and dry outdoor sitting need a spatial solution beyond individual accessories.|Compare a modest freestanding pergola/covered lounge in the existing garden layout, using warm timber and pale upholstery, positioned to preserve the approved loungers and pool circulation. Keep its scale subordinate to the house.|Adds a distinct outdoor living destination and a useful connection between pool, garden and house.|It changes the exterior and introduces wind, drainage and potential planning implications; it is an option for review, not assumed permitted work.|Show model views from house, pool and neighbouring boundaries; compare sun/shade and access before choosing location, footprint or roof type.
76|Compose the roof terrace as an outdoor living room|The terrace contains three rooflights, guarding and privacy screens, which should lead the furniture arrangement.|Develop a complete terrace plan with a sheltered lounge, a compact serving point and an unobstructed door-to-outlook route around the rooflights. Integrate lightweight screening only where sightline checks justify it.|A purposeful outdoor room instead of furniture scattered around roof constraints.|Available seating area may shrink once realistic circulation, wind restraint, roof loading and drainage are accounted for.|Render seated and standing views, rooflight access and occupied routes; coordinate the threshold, falls and structural limits separately.
79|Design the workshop as a flexible creative studio|The detached workshop has a main bench and mobile centre table, but its activities and storage need to define the layout.|Develop a complete workshop arrangement with a continuous tool/storage wall, a clear central assembly zone and a cleaner design/project corner. Separate dusty work from clean storage through layout and local extraction rather than filling every wall indiscriminately.|Turns the outbuilding into a useful second working destination with space for real projects.|The layout depends on the owner's tools and activities; extraction, power and noise provisions may be substantial.|Show a large project on the centre table, tool access, material handling through the door and a cleared alternative state.
'''
def apply(items):
 by={i['id']:i for i in items}
 for i in items:i['recommendedFirst']=False;i['substantial']=False
 for row in TEXT.strip().splitlines():
  n,title,obs,proposal,benefit,tradeoff,validation=row.split('|');x=by[f'AH-{int(n):03}']
  x.update(title=title,observation=obs,proposal=proposal,benefit=benefit,tradeoff=tradeoff,validation=validation,priority='High',scale='Large',basis='Larger design alternative — feasibility study',category='Substantial design',substantial=True,recommendedFirst=True)
  x.pop('planCaption',None)
  if int(n)==58:x['plan']='revisions/brochure-spatial-2026-09-28/plans/bar.svg'
  x['planCaption']='Baseline plan only. This larger alternative requires its own coordinated model and occupied-use checks.'
  if int(n)==14:
   x['plan']='revisions/whole-house-review-2026-09-29/model-comparisons/AH-014/plan.svg'
   x['planCaption']='Proposed round-table plan from the preview coordinates. Eight dining chair positions and 400 mm pullback outlines; 1 m scale bar. Concept, not measured survey.'
  if int(n) in (14,58):
   evidence=f'revisions/whole-house-review-2026-09-29/model-comparisons/AH-{int(n):03}/clearances.json'
   if evidence not in x['sources']:x['sources'].append(evidence)
 for x in items:
  x.pop('proposalHash',None);x['proposalHash']=hashlib.sha256(json.dumps(x,sort_keys=True,ensure_ascii=False).encode()).hexdigest()
if __name__=='__main__':
 p=HERE/'proposals.json';d=json.loads(p.read_text());apply(d['items']);d['version']=2;d['status']='100 local proposals, including 20 larger design alternatives prioritised for owner review; none applied to the approved house.';p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n');print('Prioritised',sum(i['substantial'] for i in d['items']),'larger alternatives')
