import {chromium,webkit} from 'playwright';import fs from 'node:fs/promises';import assert from 'node:assert/strict';
const base=process.env.ASHLEY_TEST_BASE||'http://127.0.0.1:8765/';const output=process.env.ASHLEY_EASTER_OUTPUT||'tests/easter/browser';await fs.mkdir(output,{recursive:true});const result={base,checks:[],errors:[]};
const chrome=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
const load=async(page,path='')=>{await page.goto(new URL(path,base).href);await page.waitForFunction(()=>window.walkthrough?.ready,null,{timeout:120000});};
try{const page=await chrome.newPage({viewport:{width:1280,height:900}});page.on('pageerror',e=>result.errors.push(e.message));await load(page);await page.click('#drag');assert.equal(await page.evaluate(()=>walkthrough.getState().room),'Outside gates');assert(await page.locator('#rooms').isVisible());assert(!await page.locator('#combat-hud').isVisible());
 await page.selectOption('#rooms','2445658-3');await page.waitForTimeout(31000);assert.equal(await page.evaluate(()=>walkthrough.easter.clock.phase),'waiting');assert.equal(await page.evaluate(()=>walkthrough.easter.pursuit.positions.length),0);result.checks.push('Unified tour starts outside; 31 seconds inside house does not trigger zombies');
 await page.selectOption('#rooms','2445694-0');await page.waitForFunction(()=>walkthrough.easter.game.state.weapon==='bow');assert.equal(await page.evaluate(()=>walkthrough.easter.clock.phase),'armed');assert.equal(await page.evaluate(()=>walkthrough.easter.game.state.wave),0);await page.evaluate(()=>walkthrough.goTo('2445658-3'));await page.waitForFunction(()=>walkthrough.easter.clock.phase==='chasing');
 await page.waitForFunction(()=>walkthrough.easter.game.state.wave===1);assert.equal(await page.evaluate(()=>walkthrough.easter.game.state.weapon),'bow');assert(!await page.locator('#rooms').isVisible());assert(await page.locator('#combat-hud').isVisible());result.checks.push('Bow collects automatically; subsequent house entry starts wave 1');
 await page.waitForFunction(()=>walkthrough.easter.pursuit.positions.length>0,null,{timeout:25000});
 await page.click('#help');const paused=await page.evaluate(()=>walkthrough.easter.clock.survived);await page.waitForTimeout(700);assert.equal(await page.evaluate(()=>walkthrough.easter.clock.survived),paused);await page.click('#drag');result.checks.push('Controls pause game clock and combat');
 // Freeze NPC routing for repeatable mesh-hit fixtures while preserving real input/projectiles.
 await page.evaluate(()=>{const w=walkthrough,g=w.easter.game;g.horde.reset();g.state.phase='rest';g.state.rest=999;w.setView([6.98,2.95,0],[0,1,0]);const a=g.horde.createActor('shambler',{x:6.98,y:4.25,z:0},[]);g.group.updateMatrixWorld(true);const p=a.figure.head.getWorldPosition(w.camera.position.clone());p.y+=.065;const o=w.camera.position;w.setView([6.98,2.95,0],[p.x-o.x,-p.z+o.z,p.y-o.y]);});
 await page.keyboard.down('Space');await page.waitForTimeout(1150);await page.screenshot({path:output+'/drawn-bow.png'});await page.keyboard.up('Space');await page.waitForFunction(()=>walkthrough.easter.game.state.kills>=1,null,{timeout:5000});
 let shot=await page.evaluate(()=>walkthrough.easter.game.lastShot);assert.deepEqual(shot.origin,shot.muzzle);assert(Math.hypot(...shot.origin.map((n,i)=>n-shot.eye[i]))>.1);result.checks.push('Draw/release animation fires a full arrow from bow nock; actual mesh hit scores a kill');
 const guns=await page.evaluate(()=>{const w=walkthrough,g=w.easter.game,shots=[];for(const id of ['pistol','shotgun','carbine']){g.horde.reset();g.state.acquire(id);g.state.cooldown=0;g.state.reloading=0;g.equip();const a=g.horde.createActor('shambler',{x:6.98,y:4.4,z:0},[]);g.group.updateMatrixWorld(true);const p=a.figure.head.getWorldPosition(w.camera.position.clone());p.y+=.065;const o=w.camera.position;w.setView([6.98,2.95,0],[p.x-o.x,-p.z+o.z,p.y-o.y]);w.camera.updateMatrixWorld(true);g.fire();shots.push({id,before:a.maxHealth,after:a.health,shot:g.lastShot});}return shots;});for(const gun of guns){assert(gun.after<gun.before,gun.id);assert.deepEqual(gun.shot.origin,gun.shot.muzzle);assert(Math.hypot(...gun.shot.origin.map((n,i)=>n-gun.shot.eye[i]))>.3);}result.checks.push('All gun hits/tracers originate at their actual visible barrels');
 const wall=await page.evaluate(()=>{const w=walkthrough,g=w.easter.game;g.horde.reset();const s=w.nav.segments.find(s=>s.name==='Kitchen dining partition');const x=(s.a[0]+s.b[0])/2,y=(s.a[1]+s.b[1])/2;return g.hit(w.camera.position.clone().set(x-1,1.9,-y),w.camera.position.clone().set(1,0,0),2)?.wall===true;});assert(wall);result.checks.push('Solid partition blocks projectiles');const barrier=await page.evaluate(()=>{const w=walkthrough,g=w.easter.game,s=w.nav.segments.find(s=>s.name==='Kitchen dining partition');const x=(s.a[0]+s.b[0])/2,y=(s.a[1]+s.b[1])/2;w.setView([x-.31,y,0],[1,0,0]);g.state.switch('shotgun');g.state.cooldown=0;g.equip();g.fire();return g.lastShot.blockedByWall;});assert(barrier,'A barrel protruding through a wall bypassed occlusion');result.checks.push('A barrel pressed into a wall cannot shoot through it');
 await page.evaluate(()=>{const w=walkthrough,g=w.easter.game;g.horde.reset();w.setView([6.98,2.95,0],[0,1,0]);g.state.phase='wave';g.state.health=10;g.horde.startWave(1,w.nav.position,1);g.horde.createActor('shambler',{x:6.98,y:3.68,z:0},[]);});await page.locator('#caught').waitFor({state:'visible',timeout:12000});await page.click('#play-again');assert.equal(await page.evaluate(()=>walkthrough.easter.game.started),false);assert.equal(await page.evaluate(()=>walkthrough.getState().room),'Outside gates');assert(await page.locator('#rooms').isVisible());assert(!await page.locator('#combat-hud').isVisible());assert.equal(await page.evaluate(()=>walkthrough.lighting.actionMode),false);result.checks.push('Telegraphed attack depletes health; retry restores tour, bow and normal graphics');
 await load(page,'easter/');assert.equal(new URL(page.url()).pathname,new URL(base).pathname);result.checks.push('Old /easter link redirects to unified tour');await page.close();
 const mobile=await chrome.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});mobile.on('pageerror',e=>result.errors.push(e.message));await load(mobile);assert.doesNotMatch(await mobile.locator('body').innerText(),/zombie|survival|\bbow\b|after hours/i);await mobile.tap('#start');await mobile.selectOption('#rooms','2445694-0');await mobile.waitForFunction(()=>walkthrough.easter.game.state.weapon==='bow');assert.equal(await mobile.evaluate(()=>walkthrough.easter.clock.phase),'armed');assert.equal(await mobile.evaluate(()=>walkthrough.easter.game.state.wave),0);await mobile.evaluate(()=>walkthrough.goTo('2445658-3'));await mobile.waitForFunction(()=>walkthrough.easter.clock.phase==='chasing');await mobile.waitForFunction(()=>walkthrough.easter.game.started);await mobile.screenshot({path:output+'/mobile-combat.png'});
 const layout=await mobile.evaluate(()=>{const r=document.getElementById('combat-hud').getBoundingClientRect(),h=document.querySelector('header').getBoundingClientRect();return{width:innerWidth,scrollWidth:document.documentElement.scrollWidth,hudTop:r.y,headerBottom:h.bottom};});assert(layout.scrollWidth<=layout.width);assert(layout.hudTop>=layout.headerBottom);
 const ammo=await mobile.evaluate(()=>walkthrough.easter.game.state.inventory.bow.reserve);await mobile.touchscreen.tap(280,350);assert.equal(await mobile.evaluate(()=>walkthrough.easter.game.state.inventory.bow.reserve),ammo-1);assert.equal(await mobile.locator('#auto-fire-control,#fire-control').count(),0);await mobile.setViewportSize({width:844,height:390});await mobile.waitForTimeout(300);await mobile.screenshot({path:output+'/landscape-combat.png'});result.checks.push('Mobile pickup, HUD and tap-to-fire without automatic firing controls');
}catch(e){result.errors.push(e.stack);}finally{await chrome.close();}
const wk=await webkit.launch({headless:true});try{const p=await wk.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});p.on('pageerror',e=>result.errors.push(e.message));await load(p);assert.doesNotMatch(await p.locator('body').innerText(),/zombie|survival|\bbow\b|after hours/i);await p.tap('#start');await p.selectOption('#rooms','2445694-0');await p.waitForFunction(()=>walkthrough.easter.game.state.weapon==='bow');assert.equal(await p.evaluate(()=>walkthrough.easter.clock.phase),'armed');assert.equal(await p.evaluate(()=>walkthrough.easter.game.state.wave),0);await p.evaluate(()=>walkthrough.goTo('2445658-3'));await p.waitForFunction(()=>walkthrough.easter.clock.phase==='chasing');await p.waitForFunction(()=>walkthrough.easter.game.state.wave===1);await p.waitForFunction(()=>walkthrough.easter.pursuit.positions.length>0,null,{timeout:30000});await p.screenshot({path:output+'/webkit-combat.png'});result.checks.push('WebKit mobile unified pickup and survival');}catch(e){result.errors.push('WebKit '+e.stack);}finally{await wk.close();}result.status=result.errors.length?'failed':'passed';await fs.writeFile(output+'/results.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));if(result.errors.length)process.exitCode=1;
