// Complete native door poses and one-person use within the retained garden rooms.
import fs from'node:fs';import assert from'node:assert/strict';import{Navigation}from'../src/navigation.js';import{restrictNavigation}from'./restrict-navigation.mjs';
const root=new URL('../../',import.meta.url),variant=process.env.GARDENHOUSE_VARIANT??'compact',dir=new URL(`revisions/interiors-overnight-2026-09-27/gardenhouse/${variant}/`,root),base=JSON.parse(fs.readFileSync(process.env.GARDENHOUSE_NAV??new URL('preview-navigation.json',dir))),exact=JSON.parse(fs.readFileSync(new URL('details-audit.json',dir))),z=.5445870161056519,reports=[];
const states=[{name:'summer room',bounds:[14.37,19.69,16.14,23.44],origin:[14.84,21.1],targets:[['bench approach',15.22,20.74],['drinks',15.28,21.35],['changing seat',15.30,22.77]]},{name:'outside WC',bounds:[14.36,24.63,16.16,26.19],origin:[14.71,25.42],targets:[['basin use',14.87,25.36],['WC use',14.88,25.70]]},{name:'tool store',bounds:[14.36,23.59,16.16,24.49],origin:[14.72,24.04],targets:[['tool access',15.49,24.04]]}];
for(const state of states){
 const nav=new Navigation({...base,obstacles:[...base.obstacles.filter(o=>!o.name.startsWith('Gardenhouse 01 | wc door')&&!o.name.startsWith('Gardenhouse 01 | tool door')&&!o.name.startsWith('Gardenhouse 01 | summer glazed door')),...exact.doors.flatMap(d=>d.poses.open)]});nav.radius=.3;
 const[x0,y0,x1,y1]=state.bounds,step=.015,nx=Math.floor((x1-x0)/step)+1,ny=Math.floor((y1-y0)/step)+1,point=i=>({x:x0+i%nx*step,y:y0+Math.floor(i/nx)*step,z});restrictNavigation(nav,state.bounds,z);
 const free=new Uint8Array(nx*ny),seen=new Uint8Array(nx*ny);for(let i=0;i<free.length;i++){const p=point(i);free[i]=Math.abs((nav.support(p.x,p.y,z)??99)-z)<.025&&!nav.blocked(p.x,p.y,z);}
 function nearest(x,y){let index=-1,distance=Infinity;for(let i=0;i<free.length;i++)if(free[i]){const p=point(i),d=Math.hypot(x-p.x,y-p.y);if(d<distance){index=i;distance=d;}}return{index,distance};}
 const origin=nearest(...state.origin);const queue=origin.index<0?[]:[origin.index];if(queue.length)seen[origin.index]=1;
 for(let q=0;q<queue.length;q++){const i=queue[q],p=point(i),ix=i%nx,iy=Math.floor(i/nx);for(const[dx,dy]of[[1,0],[-1,0],[0,1],[0,-1]]){const x=ix+dx,y=iy+dy,j=x+y*nx;if(x<0||y<0||x>=nx||y>=ny||seen[j]||!free[j])continue;const t=point(j);nav.position={...p};nav.move(t.x-p.x,t.y-p.y);if(Math.hypot(nav.position.x-t.x,nav.position.y-t.y)<.001){seen[j]=1;queue.push(j);}}}
 const checks=state.targets.map(([label,x,y])=>{const p=nearest(x,y);return{label,distance:p.distance,reachable:!!seen[p.index]};});reports.push({state:state.name,bodyWidth:.6,origin,checks});console.log(JSON.stringify(reports.at(-1)));
}
const status=reports.every(r=>r.origin.distance<.035&&r.checks.every(c=>c.distance<.045&&c.reachable))?'PASS':'FAIL';fs.writeFileSync(new URL(`../plan-${variant}.json`,dir),JSON.stringify({status,reports,note:'Separate single-user WC and narrow tool store. Exterior thresholds tested separately.'},null,2)+'\n');assert.equal(status,'PASS');
