// Pool route, lounger side access, pavilion seating and outside-WC approach.
import fs from'node:fs';import assert from'node:assert/strict';import{Navigation}from'../src/navigation.js';import{restrictNavigation}from'./restrict-navigation.mjs';
const root=new URL('../../',import.meta.url),cfg=JSON.parse(fs.readFileSync(new URL('proposal/interiors/leisure/poolgarden.json',root))),native=process.env.POOLGARDEN_NAV,base=JSON.parse(fs.readFileSync(native??new URL('output-proposed-compact/navigation.json',root))),z=.2;
const item=(name,box,top=1.3)=>({name,box,bottom:z,top:z+top}),removed=['Proposal | Pool lounger','Proposal | Pavilion sofa','Proposal | Pavilion drinks counter','Proposal | Pavilion drinks cabinet','Proposal | Pavilion counter'];
const furniture=[...cfg.loungers.map(([x,y],i)=>{const a=cfg.loungerAngleDegrees*Math.PI/180;return{name:'lounger '+i,polygon:[[-1.025,-.39],[1.025,-.39],[1.025,.39],[-1.025,.39]].map(([u,v])=>[x+u*Math.cos(a)-v*Math.sin(a),y+u*Math.sin(a)+v*Math.cos(a)]),bottom:z,top:z+1.07};}),...cfg.sideTables.map(([x,y,r])=>item('side table',[x-r,y-r,x+r,y+r],.47)),item('sofa',cfg.sofa),item('towel cupboard',cfg.towelStorage),item('coffee table',[cfg.coffeeTable[0]-.28,cfg.coffeeTable[1]-.28,cfg.coffeeTable[0]+.28,cfg.coffeeTable[1]+.28],.4)];
const states={ordinary:[],loungerUse:[item('person accessing southern lounger',[5.25,16.77,5.70,17.37])],sofaOccupied:[item('sofa knees',[12.58,20.23,13.09,22.20],.51)],towelUse:[item('towel user',[12.44,25.05,13.04,25.65])]},reports=[];
for(const[state,extra]of Object.entries(states)){
 const nav=new Navigation({...base,obstacles:[...base.obstacles.filter(o=>!removed.some(p=>o.name.startsWith(p))),...(native?[]:furniture),...extra]});nav.radius=.3;
 const x0=3.90,y0=15.13,step=.03,nx=344,ny=378,point=i=>({x:x0+i%nx*step,y:y0+Math.floor(i/nx)*step,z});restrictNavigation(nav,[x0,y0,14.21,26.44],z);
 const free=new Uint8Array(nx*ny),seen=new Uint8Array(nx*ny);for(let i=0;i<free.length;i++){const p=point(i);free[i]=Math.abs((nav.support(p.x,p.y,z)??99)-z)<.025&&!nav.blocked(p.x,p.y,z);}
 function nearest(x,y){let index=-1,distance=Infinity;for(let i=0;i<free.length;i++)if(free[i]){const p=point(i),d=Math.hypot(x-p.x,y-p.y);if(d<distance){index=i;distance=d;}}return{index,distance};}
 const origin=nearest(10.80,15.45);assert(origin.distance<.05);const queue=[origin.index];seen[origin.index]=1;
 for(let q=0;q<queue.length;q++){const i=queue[q],p=point(i),ix=i%nx,iy=Math.floor(i/nx);for(const[dx,dy]of[[1,0],[-1,0],[0,1],[0,-1]]){const x=ix+dx,y=iy+dy,j=x+y*nx;if(x<0||y<0||x>=nx||y>=ny||seen[j]||!free[j])continue;const t=point(j);nav.position={...p};nav.move(t.x-p.x,t.y-p.y);if(Math.hypot(nav.position.x-t.x,nav.position.y-t.y)<.001){seen[j]=1;queue.push(j);}}}
 let targets=[['south lounger',5.69,17.35],['middle lounger',5.69,19.95],['north lounger',5.69,22.55],['north pool route',8.25,24.53],['east pool route',10.76,18.80],['spa approach',11.00,16.32],['pavilion sofa',12.60,20.10],['towels',12.74,25.36],['outside WC approach',13.78,25.42],['tool store approach',13.78,24.04],['summer house approach',13.54,22.90]];
 if(state==='loungerUse')targets=targets.filter(t=>t[0]!=='south lounger');if(state==='sofaOccupied')targets=targets.filter(t=>t[0]!=='pavilion sofa');if(state==='towelUse')targets=targets.filter(t=>t[0]!=='towels');
 const checks=targets.map(([label,x,y])=>{const p=nearest(x,y);return{label,distance:p.distance,reachable:!!seen[p.index]};});reports.push({state,bodyWidth:.6,checks});console.log(JSON.stringify(reports.at(-1)));
}
const status=reports.every(r=>r.checks.every(c=>c.distance<.06&&c.reachable))?'PASS':'FAIL';fs.writeFileSync(new URL('revisions/interiors-overnight-2026-09-27/poolgarden/plan-compact.json',root),JSON.stringify({status,reports},null,2)+'\n');assert.equal(status,'PASS');
