import test from 'node:test';import assert from 'node:assert/strict';import * as THREE from 'three';import {bowModel,arrowModel,gunModel,supplyModel,placeArrowAtHit} from '../src/weapon-models.js';
test('bow faces forward; drawing moves string and arrow back, release flexes limbs',()=>{const bow=bowModel({held:true}),string=bow.getObjectByName('Bow string'),nock=bow.getObjectByName('Projectile origin'),limbs=bow.getObjectByName('Flexible bow limbs');const initial=[...limbs.geometry.attributes.position.array];assert(nock.position.z>0);bow.userData.animate(1,0,true);assert(nock.position.z>.29);assert.equal(string.geometry.attributes.position.getZ(1),Math.fround(nock.position.z));assert.notDeepEqual([...limbs.geometry.attributes.position.array],initial);bow.userData.animate(0,.15,false);assert.equal(bow.getObjectByName('Nocked arrow').visible,false);assert(Math.abs(nock.position.z)<.1);});
test('arrow has a long shaft, arrowhead and three visible feathers pointing down -Z',()=>{const a=arrowModel(),box=new THREE.Box3().setFromObject(a),size=box.getSize(new THREE.Vector3());assert(size.z>.7);assert(size.x>.07);let feathers=0;a.traverse(o=>{if(o.name==='Arrow feather')feathers++;});assert.equal(feathers,3);assert(box.max.z<.05);assert(box.min.z<-.7);});
test('each gun has its projectile origin immediately ahead of the visible barrel',()=>{for(const id of ['pistol','shotgun','carbine']){const gun=gunModel(id),m=gun.getObjectByName('Projectile origin'),rim=gun.getObjectByName('Muzzle rim');assert(Math.abs(m.position.x-rim.position.x)<1e-6);assert(Math.abs(m.position.y-rim.position.y)<1e-6);assert(m.position.z<rim.position.z&&rim.position.z-m.position.z<.02);}});
test('health and ammo have distinct multipart silhouettes instead of a single cube',()=>{for(const kind of ['health','ammo']){const g=supplyModel(kind);let meshes=0;g.traverse(o=>{if(o.isMesh)meshes++;});assert(meshes>10);assert(g.name.includes(kind==='health'?'satchel':'quiver'));}});
test('arrows bury their heads in the struck body and retain full length through scaled joint motion',()=>{
 const scene=new THREE.Scene(),joint=new THREE.Group();joint.position.set(2,1,-3);joint.rotation.set(.2,.4,-.3);joint.scale.set(1.26,1.06,1.18);scene.add(joint);
 const body=new THREE.Mesh(new THREE.BoxGeometry(.4,.6,.25),new THREE.MeshBasicMaterial());body.rotation.set(.1,.2,.3);joint.add(body);scene.updateMatrixWorld(true);
 const center=body.getWorldPosition(new THREE.Vector3()),direction=new THREE.Vector3(.08,-.03,-1).normalize(),ray=new THREE.Raycaster(center.clone().addScaledVector(direction,-2),direction),hit=ray.intersectObject(body)[0];assert(hit);
 const arrow=arrowModel();scene.add(arrow);placeArrowAtHit(arrow,{...hit,actor:0},direction);scene.updateMatrixWorld(true);
 const head=arrow.getObjectByName('Arrowhead'),attr=head.geometry.attributes.position;let tip=new THREE.Vector3();for(let i=0;i<attr.count;i++){const p=new THREE.Vector3().fromBufferAttribute(attr,i);if(p.y>tip.y)tip=p;}tip=head.localToWorld(tip);
 const offset=tip.clone().sub(hit.point);assert(Math.abs(offset.dot(direction)-.09)<1e-6);assert(offset.clone().cross(direction).length()<1e-6);assert.equal(arrow.parent,body);
 const nock=arrow.localToWorld(new THREE.Vector3()),length=nock.distanceTo(tip),localTip=body.worldToLocal(tip.clone());joint.position.x+=.7;joint.rotation.y+=.8;scene.updateMatrixWorld(true);
 const movedTip=body.localToWorld(localTip.clone());assert(arrow.localToWorld(new THREE.Vector3(0,0,-.7075)).distanceTo(movedTip)<1e-6);assert(Math.abs(arrow.localToWorld(new THREE.Vector3()).distanceTo(movedTip)-length)<1e-6);
});
test('wall impacts remain on the surface instead of using zombie penetration',()=>{
 const arrow=arrowModel(),wall=new THREE.Mesh(new THREE.BoxGeometry(1,1,.2),new THREE.MeshBasicMaterial()),direction=new THREE.Vector3(0,0,-1);wall.updateMatrixWorld();const hit=new THREE.Raycaster(new THREE.Vector3(0,0,2),direction).intersectObject(wall)[0];placeArrowAtHit(arrow,hit,direction);arrow.updateMatrixWorld(true);assert(arrow.localToWorld(new THREE.Vector3(0,0,-.7075)).distanceTo(hit.point)<1e-6);assert.equal(arrow.parent,null);
});
